NREL/OpenStudio

openstudiocore/src/project/ProblemRecord.cpp
openstudiocore/src/project/Test/ProblemRecord_GTest.cpp

This fixes the problem I e-mailed you about @macumber.

Deserialize rubycontinuousvariables

---

openstudiocore/src/model/AvailabilityManagerScheduled.cpp

Fix crash on removing air system schedule

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVAC.cpp

Fix SPM Magic when there are two fans

---

openstudiocore/src/model/ChillerElectricEIR.cpp
openstudiocore/src/model/ChillerElectricEIR.hpp
openstudiocore/src/model/CoilCoolingDXTwoSpeed.cpp
openstudiocore/src/model/CoilCoolingDXTwoSpeed.hpp
openstudiocore/src/model/CoilCoolingWater.cpp
openstudiocore/src/model/CoilCoolingWater.hpp
openstudiocore/src/model/CoilHeatingDXSingleSpeed.cpp
openstudiocore/src/model/CoilHeatingDXSingleSpeed.hpp
openstudiocore/src/model/CoilHeatingElectric.cpp
openstudiocore/src/model/CoilHeatingElectric.hpp
openstudiocore/src/model/CoilHeatingGas.cpp
openstudiocore/src/model/CoilHeatingGas.hpp
openstudiocore/src/model/CoilHeatingWater.cpp
openstudiocore/src/model/CoilHeatingWater.hpp
openstudiocore/src/model/FanConstantVolume.cpp
openstudiocore/src/model/FanConstantVolume.hpp
openstudiocore/src/model/FanOnOff.cpp
openstudiocore/src/model/FanOnOff.hpp
openstudiocore/src/model/FanVariableVolume.cpp
openstudiocore/src/model/FanVariableVolume.hpp
openstudiocore/src/model/HVACTemplates.cpp

These default the curves and availability schedule so that all objects
can be constructed by only passing model.
[#84205966]

Overload ctors for HVAC components

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneControlHumidistat.cpp
openstudiocore/src/openstudio_lib/ThermalZonesGridView.cpp

Fix orphan humidistat

---

CMakeLists.txt
dependencies/Boost/fchmodat.patch

Patch boost super build on mac

---

openstudiocore/src/openstudio_app/OpenStudioApp.cpp

Show errors, warnings, and untranslated objects.
[#82712360]

Improve IDF import log message

---

developer/ruby/CheckForQObject.rb
openstudiocore/src/model/AirConditionerVariableRefrigerantFlow_Impl.hpp
openstudiocore/src/model/CMakeLists.txt
openstudiocore/src/model/CoilCoolingDXVariableRefrigerantFlow_Impl.hpp
openstudiocore/src/model/CoilCoolingLowTempRadiantVarFlow_Impl.hpp
openstudiocore/src/model/CoilCoolingWaterToAirHeatPumpEquationFit_Impl.hpp
openstudiocore/src/model/CoilHeatingDXVariableRefrigerantFlow_Impl.hpp
openstudiocore/src/model/CoolingTowerPerformanceCoolTools_Impl.hpp
openstudiocore/src/model/CoolingTowerPerformanceYorkCalc_Impl.hpp
openstudiocore/src/model/CoolingTowerVariableSpeed_Impl.hpp
openstudiocore/src/model/ZoneHVACLowTempRadiantVarFlow_Impl.hpp
openstudiocore/src/model/ZoneHVACTerminalUnitVariableRefrigerantFlow_Impl.hpp

Remove q object

---

openstudiocore/src/openstudio_lib/SpaceTypesGridView.cpp
openstudiocore/src/shared_gui_components/OSGridController.cpp

1506 grid view header label

---

openstudiocore/src/energyplus/ForwardTranslator.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSurface.cpp

Fixes #1299

---

openstudiocore/src/openstudio_lib/ScriptsTabView.cpp
openstudiocore/src/shared_gui_components/MeasureManager.cpp
openstudiocore/src/shared_gui_components/MeasureManager.hpp
openstudiocore/src/shared_gui_components/VariableList.cpp

Translate model to workspace on MeasureManager::updateMeasures

---

openstudiocore/resources/CMakeLists.txt
openstudiocore/resources/energyplus/Office_With_Many_HVAC_Types/in.idf
openstudiocore/src/utilities/sql/SqlFile_Impl.cpp
openstudiocore/src/utilities/sql/Test/SqlFileFixture.cpp
openstudiocore/src/utilities/sql/Test/SqlFileFixture.hpp
openstudiocore/src/utilities/sql/Test/SqlFile_GTest.cpp

88239574 sql annual total cost

---

openstudiocore/src/osversion/VersionTranslator.cpp

Fix version translation for evap coolers

---

openstudiocore/ruby/openstudio/utilities/test/ApplicationPathHelpers_Test.rb
openstudiocore/src/utilities/CMakeLists.txt
openstudiocore/src/utilities/core/ApplicationPathHelpers.cxx.in
openstudiocore/src/utilities/core/ApplicationPathHelpers.hpp
openstudiocore/src/utilities/core/test/ApplicationPathHelpers_GTest.cpp

In order to test this we will need to have installers so we can run code using installed versions.  Since this is an addition, can we add the code, merge to develop, test installers, then proceed?  Just need sign off that these methods are ok

Energy plus dir

---

openstudiocore/src/openstudio_app/CMakeLists.txt

Fix app packaging error related to ruby bindings

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACOutdoorAirSystem.cpp

close #1676
In my tests this didn't change the energy numbers at all, but it is still is a good change to avoid improper idf.

Fix a single air to air showing up on equipment list

---

openstudiocore/ruby/openstudio/sketchup_plugin/lib/dialogs/PluginInspectorDialog.rb
openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/ConstructionBase.rb
openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/DaylightingControl.rb
openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/IlluminanceMap.rb
openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/InteriorPartitionSurface.rb
openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/InteriorPartitionSurfaceGroup.rb
openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/RenderingColor.rb
openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/ShadingSurface.rb
openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/ShadingSurfaceGroup.rb
openstudiocore/ruby/openstudio/sketchup_plugin/user_scripts/Alter or Add Model Elements/Remove_Hard_Assigned_Constructions.rb
openstudiocore/ruby/openstudio/sketchup_plugin/user_scripts/Alter or Add Model Elements/Remove_Loads_Directly_Assigned_To_Spaces.rb
openstudiocore/ruby/openstudio/sketchup_plugin/user_scripts/Alter or Add Model Elements/Remove_Orphan_SubSurfaces.rb
openstudiocore/ruby/openstudio/sketchup_plugin/user_scripts/Alter or Add Model Elements/Remove_Unused_ThermalZones.rb
openstudiocore/src/model_editor/InspectorDialog.cpp
openstudiocore/src/model_editor/InspectorDialog.hpp

This should only affect the SketchUp Plugin. This is should resolve issue #1667 unless we find other causes of mal-formed thermal zones.

Disabled ability to add or remove zones with inspector

---

openstudiocore/resources/utilities/SqlFile/1ZoneEvapCooler-V7-0-0.idf
openstudiocore/resources/utilities/SqlFile/1ZoneEvapCooler-V7-1-0.idf
openstudiocore/resources/utilities/SqlFile/1ZoneEvapCooler-V7-2-0.idf
openstudiocore/resources/utilities/SqlFile/1ZoneEvapCooler-V8-0-0.idf
openstudiocore/resources/utilities/SqlFile/1ZoneEvapCooler-V8-1-0.idf
openstudiocore/resources/utilities/SqlFile/1ZoneEvapCooler-V8-2-0.idf
openstudiocore/resources/utilities/SqlFile/1ZoneEvapCooler-V8-3-0.idf
openstudiocore/resources/utilities/SqlFile/Reproduce.txt
openstudiocore/src/pat_app/Measures/CalibrationReports/tests/CalibrationReports_Test.rb
openstudiocore/src/utilities/core/Compare.cpp
openstudiocore/src/utilities/sql/SqlFileEnums.hpp
openstudiocore/src/utilities/sql/SqlFile_Impl.cpp
openstudiocore/src/utilities/sql/SqlFile_Impl.hpp
openstudiocore/src/utilities/sql/Test/SqlFile_GTest.cpp

@axelstudios this is ready to merge to release

1692 timeseries bug

---

openstudiocore/src/model/ThermalZone.cpp

close #1687 
Ok this is the one that actually fixes #1687.  Pardon my error listing this issue while meaning to close #1686

Fix orphaned connection on zone remove

---

CMakeLists.txt

Fixes a couple of random issues for getting CI working on Windows again.

Build fixes 20150727

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslatePlantLoop.cpp

When generating component setpoint operation schemes, OpenStudio
incorrectly used the component outlet node as the demand calculation
node, when it should be the component inlet node.
fix #1709

Fix component setpoint scheme

---

openstudiocore/src/energyplus/ForwardTranslator.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslatePlantLoop.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateWaterHeaterHeatPump.cpp
openstudiocore/src/model/WaterHeaterStratified.cpp
openstudiocore/src/model/WaterHeaterStratified_Impl.hpp

Fix bad interaction between HPWH and stratified tank

---

openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml

Zone Terminal Unit List should be hidden.
close #1656

Fix IG policy for VRF

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACWaterToAirHeatPump.cpp
openstudiocore/src/model/ZoneHVACWaterToAirHeatPump.cpp

Add support for CoilHeatingWaterToAirHeatPumpVariableSpeedEquationFit
and CoilCoolingWaterToAirHeatPumpVariableSpeedEquationFit on
ZoneHVACWaterToAirHeatPump and AirLoopHVACUnitarySystem

Fixup variable speed equipment fit HP coils

---

openstudiocore/src/energyplus/ForwardTranslator.cpp
openstudiocore/src/energyplus/ForwardTranslator.hpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilCoolingDXVariableSpeed.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingDXVariableSpeed.cpp

They need to be within a CoilSystem when directly on an AirloopHVAC.

Fix variable speed coils on AirloopHVAC

---

openstudiocore/src/model/AirLoopHVAC.cpp
openstudiocore/src/model/test/AirLoopHVAC_GTest.cpp

Fix AVM Night cycle bug

---

openstudiocore/src/openstudio_lib/GridItem.cpp

Fixes #1749
This changes from using istringequal() to find() since “MaximumTemperature” and “MinimumTemperature” are valid Temperature options as well.

Change SPM icon search

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateWaterHeaterStratified.cpp

Fix water heater stratified translation bug

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/model/AirTerminalSingleDuctVAVReheat.cpp

Change VAV terminal to autosize instead of autocalculate

---

openstudiocore/resources/model/OpenStudio.idd

Fix CoilCoolingWater ip units

---

openstudiocore/src/model/PumpConstantSpeed.cpp
openstudiocore/src/model/test/PumpConstantSpeed_GTest.cpp

Fix PumpConstantSpeed::setPumpFlowRateSchedule

---

openstudiocore/src/openstudio_app/Resources/hvaclibrary/hvac_library.osm

Change from SetpointModulated to NotModulated

Change default boiler flow mode in library

---

openstudiocore/src/model/LoadProfilePlant.cpp

Fix LoadProfilePlant default load schedule

---

openstudiocore/src/openstudio_app/Resources/hvaclibrary/hvac_library.osm

Change SPM OA Reset defaults

---

openstudiocore/src/model/Splitter.cpp
openstudiocore/src/model/test/PlantLoop_GTest.cpp

Fix PlantLoop::remove

---

openstudiocore/src/pat_app/Measures/RadianceMeasure/measure.rb
openstudiocore/src/pat_app/Measures/RadianceMeasure/measure.xml

This is a candidate for 1.9.0
@rpg777 can you verify this still works for you locally?
@evanweaver @axelstudios FYI

Fixing RadianceMeasure to work on the server

---

openstudiocore/src/model/HVACComponent.cpp
openstudiocore/src/model/test/BoilerHotWater_GTest.cpp

Fix orphan node

---

openstudiocore/src/model/SpaceType.hpp
openstudiocore/src/openstudio_lib/DesignDayGridView.cpp
openstudiocore/src/openstudio_lib/FacilityExteriorEquipmentGridView.cpp
openstudiocore/src/openstudio_lib/FacilityShadingGridView.cpp
openstudiocore/src/openstudio_lib/SpaceTypesGridView.cpp
openstudiocore/src/openstudio_lib/SpacesInteriorPartitionsGridView.cpp
openstudiocore/src/openstudio_lib/SpacesLoadsGridView.cpp
openstudiocore/src/openstudio_lib/SpacesShadingGridView.cpp
openstudiocore/src/openstudio_lib/SpacesSpacesGridView.cpp
openstudiocore/src/openstudio_lib/SpacesSubsurfacesGridView.cpp
openstudiocore/src/openstudio_lib/SpacesSurfacesGridView.cpp
openstudiocore/src/shared_gui_components/OSGridController.cpp
openstudiocore/src/shared_gui_components/OSGridController.hpp

@asparke2 @DavidGoldwasser @macumber @kbenne

Gridview inheritance

---

openstudiocore/src/model/LayeredConstruction.cpp
openstudiocore/src/model/PlanarSurface.cpp
openstudiocore/src/pat_app/Measures/RadianceMeasure/measure.rb
openstudiocore/src/pat_app/Measures/RadianceMeasure/measure.xml
openstudiocore/src/runmanager/lib/EnergyPlusPreProcessJob.cpp

@rpg777 can you see if this works for you?

Fixes #1902 [#105768786]

---

openstudiocore/src/model/SetpointManagerFollowGroundTemperature.cpp
openstudiocore/src/model/SetpointManagerFollowOutdoorAirTemperature.cpp
openstudiocore/src/model/SetpointManagerFollowSystemNodeTemperature.cpp
openstudiocore/src/model/SetpointManagerScheduled.cpp
openstudiocore/src/model/SetpointManagerScheduledDualSetpoint.cpp

Allow some SPMs on plant demand

---

openstudiocore/src/energyplus/ForwardTranslator.cpp

Fix bug related to op scheme schedule

---

openstudiocore/ruby/openstudio/sketchup_plugin/resources/templates/MinimalTemplate.osm
openstudiocore/ruby/openstudio/sketchup_plugin/resources/templates/empty.osm
openstudiocore/src/openstudio_app/Resources/CECTemplate.osm
openstudiocore/src/openstudio_app/Resources/FullServiceRestaurant.osm
openstudiocore/src/openstudio_app/Resources/Hospital.osm
openstudiocore/src/openstudio_app/Resources/LargeHotel.osm
openstudiocore/src/openstudio_app/Resources/MidriseApartment.osm
openstudiocore/src/openstudio_app/Resources/MinimalTemplate.osm
openstudiocore/src/openstudio_app/Resources/Office.osm
openstudiocore/src/openstudio_app/Resources/OutPatient.osm
openstudiocore/src/openstudio_app/Resources/PrimarySchool.osm
openstudiocore/src/openstudio_app/Resources/QuickServiceRestaurant.osm
openstudiocore/src/openstudio_app/Resources/Retail.osm
openstudiocore/src/openstudio_app/Resources/SecondarySchool.osm
openstudiocore/src/openstudio_app/Resources/SmallHotel.osm
openstudiocore/src/openstudio_app/Resources/StripMall.osm
openstudiocore/src/openstudio_app/Resources/SuperMarket.osm
openstudiocore/src/openstudio_app/Resources/Warehouse.osm

Updated templates to 1.9.5

---

openstudiocore/src/model/PlanarSurface.cpp
openstudiocore/src/model/test/Surface_GTest.cpp

Change so empty constructions are no longer classified as air walls

---

openstudiocore/src/model/AirTerminalSingleDuctConstantVolumeFourPipeInduction.cpp
openstudiocore/src/model/AirTerminalSingleDuctParallelPIUReheat.cpp
openstudiocore/src/model/AirTerminalSingleDuctSeriesPIUReheat.cpp
openstudiocore/src/model/test/AirTerminalSingleDuctConstantVolumeFourPipeInduction_GTest.cpp
openstudiocore/src/model/test/AirTerminalSingleDuctParallelPIUReheat_GTest.cpp
openstudiocore/src/model/test/AirTerminalSingleDuctSeriesPIUReheat_GTest.cpp

Fix problem removing terminals that recirculate air

---

openstudiocore/src/shared_gui_components/OSGridController.cpp

Do not merge prior to 1.10 release.

107959140 select all

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSizingZone.cpp
openstudiocore/src/model/SizingZone.cpp
openstudiocore/src/model/SizingZone.hpp
openstudiocore/src/model/SizingZone_Impl.hpp
openstudiocore/src/osversion/VersionTranslator.cpp

1947 sizing zone

---

openstudiocore/OpenStudioCoreConfig.cmake.in

Add exports for Geo lib

---

openstudiocore/src/model/ThermalZone.cpp
openstudiocore/src/model/ZoneControlContaminantController.cpp
openstudiocore/src/model/ZoneControlContaminantController.hpp
openstudiocore/src/model/ZoneControlContaminantController_Impl.hpp
openstudiocore/src/model/ZoneControlHumidistat.cpp
openstudiocore/src/model/ZoneControlHumidistat.hpp
openstudiocore/src/model/ZoneControlHumidistat_Impl.hpp
openstudiocore/src/model/test/ThermalZone_GTest.cpp

close #2049 
Hey @macumber. This should make you happy. I bet we can still pick something out, but far more robust than where we were.

Fix zone controller ownership

---

openstudiocore/src/utilities/bcl/templates/ReportingMeasure/tests/reporting_measure_test.rb

Now uses version translation like the model measure template.

Updating test of template reporting measure

---

openstudiocore/resources/model/OpenStudio.idd

This takes care of an issue with curve limits and switching to IP units.
Prior to this fix, the min/max would be limited to 0/1 when in IP units.
close #1897

Fix issue with curve min/max

---

openstudiocore/resources/model/OpenStudio.idd

IDD add IP units to water flow rate fields

---

openstudiocore/src/pat_app/Measures/StandardReports/measure.xml
openstudiocore/src/pat_app/Measures/StandardReports/resources/os_lib_reporting.rb
openstudiocore/src/pat_app/Measures/StandardReports/tests/EdgeCaseModel.osm
openstudiocore/src/pat_app/Measures/StandardReports/tests/EmptyModel.osm
openstudiocore/src/pat_app/Measures/StandardReports/tests/ExampleModel.osm
openstudiocore/src/pat_app/Measures/StandardReports/tests/NoRunPeriod.osm

Earlier commit changed uuid in xml. This changes it back. Also has commit to fix test models that were corrupt, shift over zone temp condition heat map colors, and swap heating and cooling setpoint for air loop summary. Tested locally. I'll wait to merge until I see if all builds work here.

misc updates copied from measure repo

---

openstudiocore/src/pat_app/ExportXML.cpp
openstudiocore/src/shared_gui_components/VariableList.cpp

Fixes #2088, fixes #1349.  Needs to be in 1.10.5 for Elizabeth.

2088 xml export measure names

---

openstudiocore/src/pat_app/Measures/StandardReports/measure.xml
openstudiocore/src/pat_app/Measures/StandardReports/resources/os_lib_reporting.rb

@asparke2 now only warns if off by 1 m^2 or more.

Standard report area check tol

---

openstudiocore/src/pat_app/PatMainMenu.cpp
openstudiocore/src/pat_app/RunView.cpp

Disable cloud until OS 2.0, fixes #2094

---

openstudiocore/src/openstudio_lib/FileOperations.cpp
openstudiocore/src/openstudio_lib/MainTabView.cpp
openstudiocore/src/shared_gui_components/EditView.cpp

@macumber my fingers are crossed.

[#114600717] OpenStudio App loses weather file #1915

---

openstudiocore/src/openstudio_lib/HVACSystemsController.cpp

Alphabetize hvac system list

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingWaterToAirHeatPumpEquationFit.cpp

close #2043
@eringold take a look and see if you think this takes care of it.

Fix bug translating heat pump to idf format

---

openstudiocore/resources/energyplus/ProposedEnergy+.idd

Fix failing IDF import

---

openstudiocore/src/openstudio_lib/GridItem.cpp

Fix bug in hvac layout

---

openstudiocore/src/pat_app/Measures/StandardReports/measure.xml
openstudiocore/src/pat_app/Measures/StandardReports/resources/os_lib_reporting.rb

I did E+ run to confirm that this fixed the SQL query.

Update sql query for time of peak for EnergyPlus 8.5

---

openstudiocore/src/model/AirLoopHVAC.cpp
openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml

Fix crash if AirLoopHVAC::availabilitySchedule is not set

---

openstudiocore/src/openstudio_lib/OSDocument.cpp

Fix crash after apply measure now

---

openstudiocore/src/model/HVACTemplates.cpp
openstudiocore/src/openstudio_app/Resources/hvaclibrary/hvac_library.osm
openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml

2046 chiller curves

---

dependencies/ruby/Gemfile
dependencies/ruby/Gemfile.lock

@evanweaver I tested this out on my computer and it works.  I can show you how to test it later today.

Adds openstudio-standards to ruby installed with OS

---

openstudiocore/src/airflow/Airflow.i
openstudiocore/src/airflow/contam/PrjModel.hpp
openstudiocore/src/utilities/core/CommonImport.i

All of the templated types in the CONTAM support code were not being wrapped, this pull request fixes that.

Fix CONTAM ruby support

---

dependencies/ruby/Gemfile
dependencies/ruby/Gemfile.lock

@evanweaver this new version of the gem has shorter file paths.

Updating to openstudio-standards 0.1.2 with shorter file paths

---

DarwinPostFlight.sh.in
dependencies/ruby/Gemfile

@evanweaver I think the only way to test this change is to create and run an installer on Mac.  Can you create one and @DavidGoldwasser will test?

Adds symlinks to openstudio-standards gem for Mac

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/openstudio_lib/InspectorView.cpp
openstudiocore/src/openstudio_lib/InspectorView.hpp

Allow water supplemental heating coil on PTHP

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateControllerMechanicalVentilation.cpp

close #2223 
@TiejunWu what do you think?

Change translation logic for ControllerMechanicalVentilation avail

---

openstudiocore/src/model/Gas.cpp
openstudiocore/src/model/GasMixture.cpp
openstudiocore/src/model/GasMixture_Impl.hpp
openstudiocore/src/model/Gas_Impl.hpp
openstudiocore/src/model/LayeredConstruction.cpp
openstudiocore/src/model/LayeredConstruction_Impl.hpp
openstudiocore/src/model/ModelObject.cpp
openstudiocore/src/model/ModelObject_Impl.hpp
openstudiocore/src/model/ScheduleBase.cpp
openstudiocore/src/model/ScheduleBase_Impl.hpp
openstudiocore/src/model/SiteWaterMainsTemperature.cpp
openstudiocore/src/model/SiteWaterMainsTemperature_Impl.hpp
openstudiocore/src/model/test/FenestrationMaterial_GTest.cpp
openstudiocore/src/model/test/Schedule_GTest.cpp

Remove custom ValidityReport implementations

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACOutdoorAirSystem.cpp

Move OA Mixer to end of OA system equipment list

---

openstudiocore/src/energyplus/CMakeLists.txt
openstudiocore/src/energyplus/ForwardTranslator.cpp
openstudiocore/src/energyplus/ForwardTranslator.hpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSiteGroundTemperatureDeep.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSiteGroundTemperatureShallow.cpp
openstudiocore/src/energyplus/Test/ForwardTranslator_GTest.cpp
openstudiocore/src/sdd/ForwardTranslator.cpp

Adding forward translator includes for ground temperature objects

---

openstudiocore/src/model/ZoneHVACUnitVentilator.cpp
openstudiocore/src/model/test/ZoneHVACUnitVentilator_GTest.cpp
openstudiocore/src/openstudio_app/Resources/hvaclibrary/hvac_library.osm

Fixes #2184
This fixes the bad clone implementation in UnitVentilator.
This also adds more options for ZoneHVAC:UnitVentilator in the HVAC Library.

Fix UnitVentilator bad clone

---

openstudiocore/src/energyplus/CMakeLists.txt
openstudiocore/src/energyplus/ForwardTranslator.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateRunPeriodControlDaylightSavingTime.cpp
openstudiocore/src/energyplus/ReverseTranslator.cpp
openstudiocore/src/energyplus/Test/RunPeriodControlDaylightSavingTime_GTest.cpp
openstudiocore/src/model/RunPeriodControlDaylightSavingTime.cpp
openstudiocore/src/openstudio_lib/YearSettingsWidget.cpp
openstudiocore/src/shared_gui_components/MeasureManager.cpp
openstudiocore/src/utilities/bcl/BCLMeasure.cpp
openstudiocore/src/utilities/bcl/BCLMeasure.hpp
openstudiocore/src/utilities/units/Scale.cpp
openstudiocore/src/utilities/units/Scale.hpp
openstudiocore/src/utilities/units/ScaleFactory.cpp
openstudiocore/src/utilities/units/ScaleFactory.hpp
openstudiocore/src/utilities/units/Unit.cpp
openstudiocore/src/utilities/units/test/IPUnit_GTest.cpp
openstudiocore/src/utilities/units/test/SIUnit_GTest.cpp
openstudiocore/src/utilities/units/test/ScaleFactory_GTest.cpp
openstudiocore/src/utilities/units/test/Unit_GTest.cpp

Combined bug fix branch for 1.12 
@DavidGoldwasser @asparke2 @kbenne @evanweaver

1 12 bugfixes

---

openstudiocore/src/shared_gui_components/MeasureManager.cpp
openstudiocore/src/utilities/bcl/BCLMeasure.cpp
openstudiocore/src/utilities/bcl/BCLMeasure.hpp

Also added to measure manager https://github.com/macumber/measure-manager/commit/92944e076c68cba99fe2fe561e3e93e1b71fa4c8

Update xml if required fields are missing

---

DarwinPostFlight.sh.in
dependencies/ruby/Gemfile
dependencies/ruby/Gemfile.lock

This should probably wait until 1.12.1

Updates openstudio-standards to 0.1.4 to enable Hospital

---

openstudiocore/src/model/AvailabilityManager.cpp
openstudiocore/src/model/Building.cpp
openstudiocore/src/model/RefrigerationAirChiller.cpp
openstudiocore/src/model/SimulationControl.cpp
openstudiocore/src/model/ThermalZone.cpp
openstudiocore/src/model/Thermostat.cpp
openstudiocore/src/model/WaterHeaterMixed.cpp
openstudiocore/src/model/WaterHeaterStratified.cpp
openstudiocore/src/model/YearDescription.cpp
openstudiocore/src/model/ZoneControlHumidistat.cpp
openstudiocore/src/openstudio_lib/DesignDayGridView.cpp
openstudiocore/src/openstudio_lib/FacilityExteriorEquipmentGridView.cpp
openstudiocore/src/openstudio_lib/FacilityShadingGridView.cpp
openstudiocore/src/openstudio_lib/FacilityStoriesGridView.cpp
openstudiocore/src/openstudio_lib/RefrigerationGridView.cpp
openstudiocore/src/openstudio_lib/SpaceTypesGridView.cpp
openstudiocore/src/openstudio_lib/SpacesDaylightingGridView.cpp
openstudiocore/src/openstudio_lib/SpacesInteriorPartitionsGridView.cpp
openstudiocore/src/openstudio_lib/SpacesLoadsGridView.cpp
openstudiocore/src/openstudio_lib/SpacesShadingGridView.cpp
openstudiocore/src/openstudio_lib/SpacesSubsurfacesGridView.cpp
openstudiocore/src/openstudio_lib/SpacesSubtabGridView.cpp
openstudiocore/src/openstudio_lib/SpacesSurfacesGridView.cpp
openstudiocore/src/openstudio_lib/ThermalZonesGridView.cpp

This cherry picks grid view performance increases from os_2_0_develop branch back to 1.x branch.
From testing on os_2_0_develop branch...
Running Time Self (ms) Symbol Name
12809.0ms 24.2% 0.0 openstudio::SpacesTabController::setSubTab(int)
Running Time Self (ms) Symbol Name
3465.0ms 8.5% 0.0 openstudio::SpacesTabController::setSubTab(int)

Grid view performance improvement

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp
openstudiocore/src/model/Space.cpp
openstudiocore/src/model/Space.hpp
openstudiocore/src/model/ThermalZone.cpp

@DavidGoldwasser @asparke2 what do you think about this?

Do not include area of air wall surfaces in floor area

---

DarwinPostFlight.sh.in
dependencies/ruby/Gemfile
dependencies/ruby/Gemfile.lock

Fixes 90.1-2004 Primary School issues

Updates openstudio-standards to 0.1.6

---

DarwinPostFlight.sh.in
dependencies/ruby/Gemfile
dependencies/ruby/Gemfile.lock

@evanweaver ready to roll, sorry for the delays

Updates openstudio-standards to 0.1.7

---

openstudiocore/src/model/FanConstantVolume.cpp
openstudiocore/src/model/FanVariableVolume.cpp

removed CAV and VAV fan limit from air loops

---

openstudiocore/src/pat_app/Measures/StandardReports/measure.xml
openstudiocore/src/pat_app/Measures/StandardReports/resources/os_lib_reporting.rb

Copied changes made in openstudio-measure repo so they will be in next 1.x
installer default reporting measure.
https://github.com/NREL/OpenStudio-measures/issues/8

Fix to Zone conditions (issue 81 in openstudio-measures repo)

---

openstudiocore/src/energyplus/CMakeLists.txt
openstudiocore/src/energyplus/ForwardTranslator.cpp
openstudiocore/src/energyplus/ForwardTranslator.hpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneCapacitanceMultiplierResearchSpecial.cpp
openstudiocore/src/energyplus/Test/ForwardTranslator_GTest.cpp

fixes #2354 
@macumber @shorowit

forward translating ZoneCapacitanceMultiplier:ResearchSpecial

---

openstudiocore/src/pat_app/Measures/StandardReports/measure.rb
openstudiocore/src/pat_app/Measures/StandardReports/measure.xml
openstudiocore/src/pat_app/Measures/StandardReports/resources/os_lib_reporting.rb
openstudiocore/src/pat_app/Measures/StandardReports/tests/HeatingOnly.osm
openstudiocore/src/pat_app/Measures/StandardReports/tests/OpenStudioResults_Test.rb

These changes were first made in OpenStudio-measures repo OpenStudio
Results and copied over to OpenStudio, expect for XML UID which remain
different in each copy.

Fixes Issue #2299

---

openstudiocore/CMakeLists.txt

Revised MAXILKSIZE to 0x7FFFFFFF to remove LNK1320 Fatal Error

Revised MAXILKSIZE

---

openstudiocore/src/openstudio_lib/ResultsTabView.cpp

Fix results view crash on new model

---

openstudiocore/src/openstudio_lib/SimSettingsView.cpp

Fix Shadow Calc Frequency that updates the Maximum Figures. 

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/CMakeLists.txt
openstudiocore/src/energyplus/Test/SetpointManagerFollowGroundTemperature_GTest.cpp
openstudiocore/src/model/SetpointManagerFollowGroundTemperature.cpp
openstudiocore/src/model/SetpointManagerFollowGroundTemperature.hpp
openstudiocore/src/model/SetpointManagerFollowGroundTemperature_Impl.hpp
openstudiocore/src/model/test/SetpointManagerFollowGroundTemperature_GTest.cpp

@shorowit @macumber 
https://github.com/NREL/OpenStudio-BEopt/issues/66#issuecomment-297194614

Exposing SetpointManager:FollowGroundTemperature - Reference Ground Temperature Object Type

---

openstudiocore/src/model/CoilCoolingDXSingleSpeed.cpp
openstudiocore/src/model/CoilCoolingDXSingleSpeed.hpp
openstudiocore/src/model/CoilCoolingDXSingleSpeed_Impl.hpp
openstudiocore/src/model/CoilCoolingDXTwoSpeed.cpp
openstudiocore/src/model/CoilCoolingDXTwoSpeed.hpp
openstudiocore/src/model/CoilCoolingDXTwoSpeed_Impl.hpp
openstudiocore/src/model/CoilHeatingWaterToAirHeatPumpEquationFit.cpp
openstudiocore/src/model/CoilHeatingWaterToAirHeatPumpEquationFit.hpp
openstudiocore/src/model/CoilHeatingWaterToAirHeatPumpEquationFit_Impl.hpp
openstudiocore/src/model/ZoneHVACWaterToAirHeatPump.cpp
openstudiocore/src/model/ZoneHVACWaterToAirHeatPump.hpp
openstudiocore/src/model/ZoneHVACWaterToAirHeatPump_Impl.hpp

Fix set methods that require an OptionalDouble

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateGroundHeatExchangerVertical.cpp
openstudiocore/src/model/GroundHeatExchangerVertical.cpp
openstudiocore/src/model/GroundHeatExchangerVertical.hpp
openstudiocore/src/model/ModelHVAC.i
openstudiocore/src/model/test/GroundHeatExchangerVertical_GTest.cpp

SWIG Wrappers for GroundHeatExchanger:Vertical gFunctions

---

openstudiocore/src/energyplus/Test/ForwardTranslator_GTest.cpp

fixing ZoneCapacitanceMultiplier Forward Translation Unit Test

---

openstudiocore/src/openstudio_app/OpenStudioApp.cpp
openstudiocore/src/openstudio_app/OpenStudioApp.hpp

use a thread to keep things going.
ref #2613

Show wait dialog while measure manager and libs are spinning up

---

openstudiocore/src/utilities/bcl/LocalBCL.cpp

Partially fixes #2665
Still would like to disable file menus while attempting to download measure, @kbenne

Return most recent version of measure when requested by uid only

---

openstudiocore/CMakeLists.txt
openstudiocore/src/model/LightsDefinition.cpp
openstudiocore/src/model/ScheduleDay.cpp
openstudiocore/src/model/ScheduleFixedInterval.cpp
openstudiocore/src/model/ScheduleVariableInterval.cpp
openstudiocore/src/model/SpaceInfiltrationDesignFlowRate.cpp
openstudiocore/src/model/test/ScheduleDay_GTest.cpp
openstudiocore/src/model/test/ScheduleInterval_GTest.cpp
openstudiocore/src/utilities/core/String.cpp
openstudiocore/src/utilities/core/String.hpp
openstudiocore/src/utilities/idf/IdfObject.cpp
openstudiocore/src/utilities/idf/Test/IdfObject_GTest.cpp
openstudiocore/src/utilities/idf/Test/WorkspaceObject_GTest.cpp

Fixed #https://github.com/NREL/OpenStudio/issues/2573
In IdfObject, now check if isnan of isinfinity.
Small Gtest added too.

Fix 2573: setDouble accepts NaNs and Infinity

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp
openstudiocore/src/energyplus/Test/ThermalZone_GTest.cpp
openstudiocore/src/model/ThermalZone.cpp
openstudiocore/src/model/test/ThermalZone_GTest.cpp

Fix 2849 and 2850 daylighting control problems (sum of frac > 1.0, and illumanceSP not translated if defaulted)

---

openstudiocore/src/energyplus/CMakeLists.txt
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
openstudiocore/src/energyplus/Test/AirLoopHVACUnitarySystem_GTest.cpp
openstudiocore/src/model/AirLoopHVACUnitarySystem.cpp
openstudiocore/src/model/AirLoopHVACUnitarySystem.hpp
openstudiocore/src/model/test/AirLoopHVACUnitarySystem_GTest.cpp
openstudiocore/src/openstudio_lib/DesignDayGridView.cpp
openstudiocore/src/openstudio_lib/FacilityStoriesGridView.cpp
openstudiocore/src/openstudio_lib/GridViewSubTab.cpp
openstudiocore/src/openstudio_lib/LuminaireInspectorView.cpp
openstudiocore/src/openstudio_lib/MainRightColumnController.cpp
openstudiocore/src/openstudio_lib/ModelObjectTypeListView.cpp
openstudiocore/src/openstudio_lib/SpaceTypesController.cpp
openstudiocore/src/openstudio_lib/SpacesSpacesGridView.cpp
openstudiocore/src/openstudio_lib/SpacesSubtabGridView.cpp
openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml
openstudiocore/src/sdd/MapHVAC.cpp

Addressed #2296, #2266 and #2152, #2778 and #2710, #2112, #2175, #86, #2463 and partially #2176.
Proof of functionaly will be provided in the respective issues thread.

Fix qt display

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslatePumpConstantSpeed.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslatePumpVariableSpeed.cpp
openstudiocore/src/model/PumpConstantSpeed.cpp
openstudiocore/src/model/PumpConstantSpeed.hpp
openstudiocore/src/model/PumpConstantSpeed_Impl.hpp
openstudiocore/src/model/PumpVariableSpeed.cpp
openstudiocore/src/model/PumpVariableSpeed.hpp
openstudiocore/src/model/PumpVariableSpeed_Impl.hpp
openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/osversion/VersionTranslator.hpp

Add new pump fields

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACTerminalUnitVariableRefrigerantFlow.cpp
openstudiocore/src/model/ZoneHVACTerminalUnitVariableRefrigerantFlow.cpp
openstudiocore/src/model/ZoneHVACTerminalUnitVariableRefrigerantFlow.hpp
openstudiocore/src/model/ZoneHVACTerminalUnitVariableRefrigerantFlow_Impl.hpp

let vrf terminal coils be optional

---

openstudiocore/src/openstudio_lib/HVACSystemsController.cpp

Fix crash while navigating SHW

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
openstudiocore/src/model/AirLoopHVACUnitarySystem.cpp
openstudiocore/src/model/AirLoopHVACUnitarySystem.hpp

also related methods ::controlType, ::resetControlType, and
controlTypeValues.
close #2855

Add AirLoopHVACUnitarySystem::setControlType

---

openstudiocore/src/model/PortList.cpp
openstudiocore/src/model/PortList.hpp
openstudiocore/src/model/PortList_Impl.hpp
openstudiocore/src/model/ThermalZone.cpp
openstudiocore/src/model_editor/IGLineEdit.cpp

See comments on #1286 to make sure this doesn't create unwanted problems.

Potential fix for #1286 to retain zero when clicking hardsize

---

openstudiocore/src/openstudio_app/Resources/hvaclibrary/hvac_library.osm

Add cooledbeamtype to hvac_library.osm. Fix #2879

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEnergyManagementSystemActuator.cpp
openstudiocore/src/energyplus/Test/EMS_GTest.cpp
openstudiocore/src/model/EnergyManagementSystemActuator.cpp
openstudiocore/src/model/EnergyManagementSystemActuator.hpp
openstudiocore/src/model/EnergyManagementSystemActuator_Impl.hpp
openstudiocore/src/model/EnergyManagementSystemSensor.cpp
openstudiocore/src/model/test/EnergyManagementSystemActuator_GTest.cpp
openstudiocore/src/model/test/EnergyManagementSystemGlobalVariable_GTest.cpp
openstudiocore/src/model/test/EnergyManagementSystemSensor_GTest.cpp
openstudiocore/src/model/test/EnergyManagementSystemTrendVariable_GTest.cpp

add EMS Actuators for SpaceLoads
change EMS Sensors constructor to use output var keyValue if not defaulted
change EMS Actuator .actuatedComponent to Optional to handle cases where the modelObject gets deleted without the knowlege of the actuator on FT

External interace

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
openstudiocore/src/model/AirTerminalDualDuctConstantVolume.cpp
openstudiocore/src/model/AirTerminalDualDuctConstantVolume.hpp
openstudiocore/src/model/AirTerminalDualDuctConstantVolume_Impl.hpp
openstudiocore/src/model/AirTerminalDualDuctVAV.cpp
openstudiocore/src/model/AirTerminalDualDuctVAV.hpp
openstudiocore/src/model/AirTerminalDualDuctVAVOutdoorAir.cpp
openstudiocore/src/model/AirTerminalDualDuctVAVOutdoorAir.hpp
openstudiocore/src/model/AirTerminalDualDuctVAVOutdoorAir_Impl.hpp
openstudiocore/src/model/AirTerminalDualDuctVAV_Impl.hpp
openstudiocore/src/model/CoolingTowerSingleSpeed.cpp
openstudiocore/src/model/CoolingTowerSingleSpeed.hpp
openstudiocore/src/model/CoolingTowerSingleSpeed_Impl.hpp
openstudiocore/src/model/CoolingTowerTwoSpeed.cpp
openstudiocore/src/model/CoolingTowerTwoSpeed.hpp
openstudiocore/src/model/CoolingTowerTwoSpeed_Impl.hpp
openstudiocore/src/model/ModelCore.i
openstudiocore/src/model/People.cpp
openstudiocore/src/utilities/core/StringHelpers.cpp
openstudiocore/src/utilities/units/QuantityRegex.cpp
openstudiocore/src/utilities/units/QuantityRegex.i
openstudiocore/src/utilities/units/test/QuantityRegex_GTest.cpp
openstudiocore/src/utilities/units/test/UnitFactory_GTest.cpp

ftH20 (zero) instead of ftH2O (capital letter) for the new pump fields

Should fix #2900 I think

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEnergyManagementSystemActuator.cpp
openstudiocore/src/energyplus/Test/EMS_GTest.cpp

tested on Scotts and my model.  Will add them to the regression tests.
Still need to deal with the multi-space per spacetype issue, but should be fine for now.

Ems zone list fix

---

openstudiocore/src/model/test/Component_GTest.cpp
openstudiocore/src/utilities/idf/Test/Validity_GTest.cpp
openstudiocore/src/utilities/idf/Test/WorkspaceObject_GTest.cpp
openstudiocore/src/utilities/idf/Test/Workspace_GTest.cpp
openstudiocore/src/utilities/idf/Workspace.cpp
openstudiocore/src/utilities/idf/Workspace.hpp

Change default Idd filetype to EnergyPlus instead of OpenStudio for Workspace

---

openstudiocore/src/energyplus/ReverseTranslator.cpp
openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateEnergyManagementSystemOutputVariable.cpp
openstudiocore/src/openstudio_app/OpenStudioApp.cpp

Avoids crash, not sure that translation is correct

---

doc/Building and Testing OpenStudio.md

@evanweaver here are the updated instructions for deploying the OpenStudio docker containers. Let me know if you have any questions.

update docker build instructions

---

openstudiocore/src/energyplus/ForwardTranslator.cpp

Fix #2989 to force initialize timestep

---

openstudiocore/src/utilities/core/ApplicationPathHelpers.cxx.in

Fix bug when calling cli in path

---

.gitlab-ci.yml

Update gitlab ci yml file

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEnergyManagementSystemSensor.cpp
openstudiocore/src/energyplus/Test/EMS_GTest.cpp
openstudiocore/src/model/test/EnergyManagementSystemSensor_GTest.cpp

resolve 
https://github.com/NREL/OpenStudio/issues/3102

resolve EMS Sensor issue 3102

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/CMakeLists.txt
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEvaporativeCoolerDirectResearchSpecial.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateLifeCycleCostParameters.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateScheduleRuleset.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneCapacitanceMultiplierResearchSpecial.cpp
openstudiocore/src/energyplus/Test/EvaporativeCoolerDirectResearchSpecial_GTest.cpp
openstudiocore/src/model/EvaporativeCoolerDirectResearchSpecial.cpp
openstudiocore/src/model/EvaporativeCoolerDirectResearchSpecial.hpp
openstudiocore/src/model/EvaporativeCoolerDirectResearchSpecial_Impl.hpp
openstudiocore/src/openstudio_app/Resources/default/hvac_library.osm
openstudiocore/src/openstudio_lib/GridItem.cpp

Making a branch to test several PRs using CI

Julien mega merge

---

openstudiocore/src/utilities/filetypes/EpwFile.cpp

@joseph-robertson can you review before I merge?
@jasondegraw FYI

Fixes #3157

---

openstudiocore/src/utilities/core/ApplicationPathHelpers.cxx.in

More debugging help and trace symlinks

---

openstudiocore/src/openstudio_lib/InspectorView.cpp

Fix #1566 - Wrong default tab for PTAC. I fixed this in two or three other occurrences I found.
**This was just an index thing.**
@macumber could you review this

Fix #1566 - Wrong default tab for PTAC

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEnergyManagementSystemInternalVariable.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEnergyManagementSystemMeteredOutputVariable.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEnergyManagementSystemOutputVariable.cpp
openstudiocore/src/energyplus/Test/EMS_GTest.cpp

addresses issue
https://github.com/NREL/OpenStudio/issues/3182
All relevant tests pass.

Ems metered output variable

---

openstudiocore/src/model/FanConstantVolume.cpp
openstudiocore/src/model/FanOnOff.cpp
openstudiocore/src/model/FanVariableVolume.cpp

Allow fans on oa system even without AirLoopHVAC

---

openstudiocore/src/model/AirLoopHVAC.cpp
openstudiocore/src/model/test/AirLoopHVAC_GTest.cpp

Fix bug in AirLoopHVAC::remove

---

dependencies/ruby/Gemfile
dependencies/ruby/Gemfile.lock
openstudiocore/CMakeLists.txt

Updates openstudio-standards to 0.2.3

Updates openstudio-standards to 0.2.3

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACEquipmentList.cpp
openstudiocore/src/energyplus/Test/ThermalZone_GTest.cpp
openstudiocore/src/model/ThermalZone.cpp
openstudiocore/src/model/ThermalZone.hpp
openstudiocore/src/model/ThermalZone_Impl.hpp
openstudiocore/src/model/ZoneHVACEquipmentList.cpp
openstudiocore/src/model/ZoneHVACEquipmentList.hpp
openstudiocore/src/model/ZoneHVACEquipmentList_Impl.hpp
openstudiocore/src/model/test/ThermalZone_GTest.cpp
openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/osversion/VersionTranslator.hpp

Fix #3257 - zone load distribution scheme

---

openstudiocore/src/openstudio_lib/GeometryEditorView.cpp
openstudiocore/src/openstudio_lib/GeometryEditorView.hpp
openstudiocore/src/openstudio_lib/GeometryTabController.cpp
openstudiocore/src/openstudio_lib/GeometryTabController.hpp
openstudiocore/src/openstudio_lib/MainRightColumnController.cpp
openstudiocore/src/openstudio_lib/library/geometry_editor_start.html

Updates as discussed with @DavidGoldwasser and @asparke2

Implemented checklist for geometry editor

---

dependencies/ruby/Gemfile
dependencies/ruby/Gemfile.lock
openstudiocore/CMakeLists.txt

Updates openstudio-standards to 0.2.5.  Only minor bugfix from 0.2.4.

Updates openstudio-standards to 0.2.5

---

openstudiocore/CMakeLists.txt

Bump to E+ 9.0.1

---

developer/ruby/UpdateHVACLibrary.rb
openstudiocore/sketchup_plugin/openstudio/sketchup_plugin/resources/templates/MinimalTemplate.osm
openstudiocore/sketchup_plugin/openstudio/sketchup_plugin/resources/templates/empty.osm
openstudiocore/src/openstudio_app/Resources/default/hvac_library.osm
openstudiocore/src/openstudio_app/Resources/default/office_default.osm

I've parallelized the `UpdateHVACLibrary.rb`
You'll need
```
gem install parallel
gem install ruby-progressbar
```
And I've run it. 
But I'm in the process of re-regenerating the openstudio-standards OSM files using https://github.com/NREL/openstudio-standards/blob/master/data/standards/export_OpenStudio_libraries.rb because I think they are way outdated
@macumber

Update libraries to 270

---

openstudiocore/src/utilities/geometry/Intersection.cpp

Minor tweak, can wait until after release

Reorder check in to avoid hitting warning

---

doc/Building and Testing OpenStudio.md

added instructions to openstudio.net update process

additional instructions to openstudio.net update process

---

CMakeLists.txt
openstudiocore/CMakeLists.txt
openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/utilities/idd/versions/2_7_0/OpenStudio.idd

Update to 2.7.1

---

openstudiocore/src/cli/CMakeLists.txt
openstudiocore/src/cli/openstudio.exe.manifest
openstudiocore/src/cli/openstudio.rc.in
openstudiocore/src/openstudio_app/CMakeLists.txt

Added details to openstudio.exe and OpenStudioApp.exe so they show up in the right-click-properties-details tab on Windows

Added properties for OpenStudio CLI and updated for OpenStudio

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEvaporativeCoolerDirectResearchSpecial.cpp
openstudiocore/src/energyplus/Test/EvaporativeCoolerDirectResearchSpecial_GTest.cpp

Fix #3363 - FT the primary air design flow rate field

Fix #3363 - FT the primary air design flow rate field

---

openstudiocore/src/radiance/ForwardTranslator.cpp
openstudiocore/src/radiance/ForwardTranslator.hpp
openstudiocore/src/radiance/Test/ForwardTranslator_GTest.cpp

Replace QPolygon with boost polygon

---

openstudiocore/embedded/embedded_files.hxx.in

Fix read past end of file with embedded files

---

openstudiocore/src/airflow/contam/ForwardTranslator.cpp
openstudiocore/src/airflow/contam/PrjReader.cpp
openstudiocore/src/airflow/contam/PrjReader.hpp
openstudiocore/src/utilities/core/Path.cpp
openstudiocore/src/utilities/core/Path.hpp
openstudiocore/src/utilities/core/String.cpp
openstudiocore/src/utilities/core/String.hpp
openstudiocore/src/utilities/core/test/String_GTest.cpp
openstudiocore/src/utilities/pch/PCH.hpp.gcc.in
openstudiocore/src/utilities/pch/PCH.hpp.msvc.in

Does not remove any code that is dependent on QDom.

Remove q textstream

---

openstudiocore/src/airflow/contam/SimFile.cpp
openstudiocore/src/gbxml/ReverseTranslator.cpp
openstudiocore/src/model_editor/InspectorDialog.cpp
openstudiocore/src/model_editor/ModalDialogs.cpp
openstudiocore/src/sdd/ReverseTranslator.cpp
openstudiocore/src/shared_gui_components/BuildingComponentDialog.cpp

Remove qt contam

---

openstudiocore/src/model/PlantLoop.cpp

need to handle the case where only the ConnectorNode exists

Fix failing plantloop clone test

---

dependencies/ruby/Gemfile
dependencies/ruby/Gemfile.lock
openstudiocore/CMakeLists.txt

Updates measure tester gem for testing

Update gem to test measure tester

---

openstudiocore/resources/CMakeLists.txt
openstudiocore/resources/simxml/OffLrg-ThermalEnergyStorage_StoragePriority-ap.xml
openstudiocore/src/sdd/Helpers.cpp
openstudiocore/src/sdd/Helpers.hpp
openstudiocore/src/sdd/MapGeometry.cpp
openstudiocore/src/sdd/MapHVAC.cpp
openstudiocore/src/sdd/MapSchedules.cpp
openstudiocore/src/sdd/ReverseTranslator.cpp
openstudiocore/src/sdd/ReverseTranslator.hpp
openstudiocore/src/sdd/SDD.i
openstudiocore/src/sdd/Test/ReverseTranslator_GTest.cpp

Updates SDD from QXml to pugixml.
Thoroughly tested about 80 OSMs for FT and same for RT. No Diffs between previous and now.
Will add link to the OpenStudio-resources PR when its ready.

Change XML library in SDD from QXml to pugixml

---

openstudiocore/src/sdd/MapHVAC.cpp

HotFix: Fix an existing error that makes ThermalStorage tests fail

HotFix: Fix an existing error that makes ThermalStorage tests fail

---

openstudiocore/src/utilities/core/ApplicationPathHelpers.cxx.in

Fix #3415 - getOpenStudioCLI in Debug on Unix

Fix #3415 - getOpenStudioCLI in Debug on Unix

---

.gitignore
openstudiocore/resources/model/OpenStudio.idd

Fix #3410 Add ASHRAETau2017 and ajust ranges for Taub/Taud in DesignDay OpenStudio.idd

Fix #3410 Add ASHRAETau2017 and ajust ranges for Taub/Taud in DesignDay OpenStudio.idd

---

openstudiocore/CMakeLists.txt

Update standards gem to 0.2.8

---

openstudiocore/CMakeLists.txt

Fix installer when app is not built

---

openstudiocore/CMakeLists.txt

Install gemspec

---

CMakeLists.txt
dependencies/ruby/build_ruby.bat.in

I made this PR as tiny as possible. 
TL;DR
- Not a linking issue
- We never properly build Debug Ruby Windows
- Bug in Ruby
- Build script fixed, Ruby upgraded

Fix Windows Ruby Debug Build Issues

---

openstudiocore/src/model/AirTerminalSingleDuctVAVReheat.cpp
openstudiocore/src/model/SizingSystem.cpp
openstudiocore/src/model/SizingSystem.hpp

Remove 2.6.2 api change warnings

---

openstudiocore/CMakeLists.txt

This is updates qt statically linked libs references in CMake for apple.

Updated qt lib s3 links for new static linked

---

openstudiocore/pat/CMakeLists.txt

Updated PAT SHA for openstudio server

---

openstudiocore/CMakeLists.txt
openstudiocore/sketchup_plugin/openstudio/sketchup_plugin/resources/templates/MinimalTemplate.osm
openstudiocore/sketchup_plugin/openstudio/sketchup_plugin/resources/templates/empty.osm
openstudiocore/src/openstudio_app/Resources/default/hvac_library.osm
openstudiocore/src/openstudio_app/Resources/default/office_default.osm
openstudiocore/src/utilities/sql/Test/SqlFile_GTest.cpp

Branch 2 8 0

---

openstudiocore/CMakeLists.txt
openstudiocore/pat/CMakeLists.txt
openstudiocore/ruby/CMakeLists.txt

A few changes to cmake for openssl_rb for mac, pat sha and mac min supported flag

updates to cmake files for openssl, pat, osx ver

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingElectric.cpp
openstudiocore/src/model/CoilHeatingElectric.cpp
openstudiocore/src/model/CoilHeatingElectric.hpp
openstudiocore/src/utilities/data/Test/TimeSeries_GTest.cpp
openstudiocore/src/utilities/data/TimeSeries.cpp

Branch 2 8 0 rc4

---

CMakeLists.txt
ConanInstall.cmake

* Moving the conan_ruby stuff into ConanInstall.cmake manually

Merge conan and ruby related stuff in OS_App_killswitch

---

Jenkinsfile_develop

Adding Jenkinsfile "Jenkinsfile_develop" to trigger CI builds in Jenkins CI for PRs to develop branch.

added Jenkins file to trigger CI builds for PR to develop

---

Jenkinsfile_develop3

Adding Jenkinsfile 'Jenkinsfile_develop3' to build PR to develop3 branch.

Added Jenkins file to build PR to develop3 branch

---

openstudiocore/CMakeLists.txt

Updating md5 hash for redhat E+ 9.1.0

updated hash for redhat energyplus 9.1.0

---

openstudiocore/src/cli/test/bundle_git/Gemfile
openstudiocore/src/model/test/ScheduleInterval_GTest.cpp
openstudiocore/src/utilities/bcl/test/BCL_GTest.cpp
openstudiocore/src/utilities/core/test/Path_GTest.cpp

fixing several unit test failures on unix

---

openstudiocore/src/shared_gui_components/OSComboBox.cpp

Fix crash when leaving tabs with combobox2

---

ConanInstall.cmake

Track NREL's openstudio_ruby 'stable'!

---

openstudiocore/src/energyplus/CMakeLists.txt
openstudiocore/src/energyplus/ForwardTranslator.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateFanConstantVolume.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateFanVariableVolume.cpp
openstudiocore/src/energyplus/Test/FanConstantVolume_GTest.cpp
openstudiocore/src/energyplus/Test/FanVariableVolume_GTest.cpp

Fix #3591: ForwardTranslate End Use by Subcategory for Fan:VariableVolume and Fan:ConstantVolume

---

openstudiocore/CMakeLists.txt
openstudiocore/src/cli/embedded_help.rb

Fixes crash in CLI if json native gem is installed

Issue 3590

---

openstudiocore/resources/energyplus/ProposedEnergy+.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateTableMultiVariableLookup.cpp
openstudiocore/src/energyplus/Test/EMS_GTest.cpp
openstudiocore/src/energyplus/Test/TableMultiVariableLookup_GTest.cpp
openstudiocore/src/model/TableMultiVariableLookup.cpp
openstudiocore/src/model/TableMultiVariableLookup.hpp
openstudiocore/src/model/test/TableMultiVariableLookup_GTest.cpp
openstudiocore/src/utilities/idd/Test/IddFactory_GTest.cpp
openstudiocore/src/utilities/idd/Test/IddFile_GTest.cpp

Fixes #3651

---

openstudiocore/src/openstudio_lib/library/geometry_preview.html

Display non-zero north angle

---

openstudiocore/resources/energyplus/ProposedEnergy+.idd
openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalStorageIceDetailed.cpp
openstudiocore/src/model/AirLoopHVACUnitarySystem.cpp

Some post-merges fixes

---

openstudiocore/CMakeLists.txt
openstudiocore/sketchup_plugin/openstudio/sketchup_plugin/resources/templates/MinimalTemplate.osm
openstudiocore/sketchup_plugin/openstudio/sketchup_plugin/resources/templates/empty.osm
openstudiocore/sketchup_plugin/openstudio/sketchup_plugin/user_scripts/On Demand Template Generators/resources/Master_Schedules.osm
openstudiocore/src/openstudio_app/Resources/default/hvac_library.osm
openstudiocore/src/openstudio_app/Resources/default/office_default.osm

Updated for EneryyPlus Offical v9.2 release and updated OSM library files.

Official EnergyPlus v9.2 release and updated OSM library files

---

openstudiocore/src/model/AvailabilityManagerNightCycle.cpp

cf https://github.com/NREL/OpenStudio/pull/3711#discussion_r332737753

#3711 followup (minor, just a comment thing)

---

openstudiocore/src/model_editor/test/InspectorDialog_GTest.cpp
openstudiocore/src/model_editor/test/ModalDialogs_GTest.cpp
openstudiocore/src/openstudio_lib/test/IconLibrary_GTest.cpp
openstudiocore/src/utilities/core/test/UpdateManager_GTest.cpp
openstudiocore/src/utilities/filetypes/test/WorkflowJSON_GTest.cpp
openstudiocore/src/utilities/plot/Test/ProgressBar_GTest.cpp
openstudiocore/src/utilities/sql/Test/IlluminanceMap_GTest.cpp

Add QtGUI_ to all unit tests that use QWidget

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateShadingControl.cpp

Fix #3710: Add new choices for Shading Control Type in IDD

Add new choices for Shading Control Type in IDD

---

openstudiocore/CMakeLists.txt
openstudiocore/src/cli/test/test_embedded_ruby.rb
openstudiocore/src/utilities/core/test/PathWatcher_GTest.cpp

Skip cli openssl check on mac

---

openstudiocore/src/model/ScheduleRule.cpp
openstudiocore/src/model/ScheduleRule.hpp
openstudiocore/src/model/ScheduleRule_Impl.hpp
openstudiocore/src/model/test/ScheduleRule_GTest.cpp

Schedule:Rule Convenience methods to get/set for Weekdays, Weekends, and AllDays

---

ConanInstall.cmake

cf https://github.com/bincrafters/conan-cpprestsdk/pull/9
closing items in https://github.com/NREL/OpenStudio/pull/3824

cpprestsdk bincrafters/stable now includes the changes we need

---

ConanInstall.cmake

cf https://github.com/conan-io/conan-center-index/issues/533
@macumber Bumped into this over the weekend.
@tijcolem This will require ensuring that the CI images have the latest conan 1.21.0

Update min version to conan 1.21.0 (to avoid issue with bzip / conan center index)

---

.gitignore

Gitignore a .clangd directory, due to my use of Vim's YouCompleteMe with clangd-completer

gitignore an IDE folder

---

CMakeLists.txt
src/osversion/VersionTranslator.cpp
src/osversion/VersionTranslator.hpp
src/utilities/idd/versions/3_0_0/OpenStudio.idd

Bumped version to 3.0.1-beta
Copy the official OpenStudio IDD 3.0.0 to the utilities/idd/3_0_0 folder
Prepare the VersionTranlator for 3.0.0 to 3.0.1

Bump version to 3.0.1

---

developer/ruby/SubProjectClassGenerators/ModelClassGenerator.rb

@joseph-robertson reported it.

Fix bug in GenerateClass.rb

---

src/utilities/sql/SqlFile_Impl.cpp

In SqlFile trap case when EnergyPlus year is 0

---

Jenkinsfile_develop_osx
Jenkinsfile_develop_ubuntu_1804
Jenkinsfile_develop_ubuntu_2004
Jenkinsfile_develop_windows
resources/model/15023_Model12.osm
resources/model/floorplan_school.osm
ruby/test/Issue_2560_Test.rb
ruby/test/Polygon3d_Join_Test.rb
ruby/test/RemoveSpikes&Overlaps_TZ46_TZ47_Test.rb
ruby/test/RemoveSpikesAndOverlaps_TZ46_TZ47_Test.rb
ruby/test/model.rb
src/model/Building.cpp
src/model/Space.cpp
src/model/Surface.cpp
src/model/test/Space_GTest.cpp
src/utilities/CMakeLists.txt
src/utilities/geometry/BoundingBox.hpp
src/utilities/geometry/Intersection.cpp
src/utilities/geometry/Polygon3d.cpp
src/utilities/geometry/Test/Intersection_GTest.cpp

Proposed changes to #4221. @ggartside I didn't want to hijack your branch so I created this one, to facilitate your review of my proposed changes. Most of them are cleanup/cosmetic, but I also re-enabled the tests to run on unix. I switched our Jenkins CI library so it would also run the disabled intersect tests (`Space_intersectSurfaces_degenerate3` for eg)
Note: for now I'm pointing to develop so that CI builds it and tests it. Then I'll change the base to @ggartside 's branch.

Geometry improvements review

---

src/utilities/geometry/Intersection.cpp

See original #4221 
fixes #4295

Geometry Improvements

---

src/utilities/geometry/FloorplanJS.cpp

Fixes #4384
This will not be exhaustively relevant to every PR.

Fixes https://github.com/NREL/OpenStudio/issues/4384

---

src/energyplus/EnergyPlus.i
src/energyplus/ForwardTranslator.cpp
src/energyplus/ForwardTranslator.hpp

- Fixes #ISSUENUMBERHERE (IF THIS IS A DEFECT)
**Labels:**
This will not be exhaustively relevant to every PR.

Add a method on the FT to get known ft options 

---

.github/workflows/buildCSharp.yml
.github/workflows/python_bindings.yml

Fixes python and csharp bindings due to conan version issue.

Fix github action build for python and csharp bindings

---

src/workflow/OSWorkflow.cpp

See a description of what is going on over on the [issue](https://github.com/NREL/OpenStudio/issues/5040)

Don't delete the osw when it is in the run dir
