NREL/OpenStudio

openstudiocore/src/model_editor/InspectorGadget.cpp

Some autosizable fields were reported to not accept 0 as a value.
Change from autosize to hardsize with 0, and the IG would appear to
accept that.  But leave IG and come back and you will find that the
field is still set to autosize.
The root of this problem seems to be that some idd fields use exclusive
limits.  ie > not >=.  However the IG input field validators don't
discern the difference and therefore just default to inclusive limits.
This lets the IG interface lead you to believe you set a value that
really didn't validate and get written to the model.
This is a change to to add / subtract epsilon if the limit is exclusive,
so that you will know right away if a value is not accepted.
[fix #85606174]
fix #1286

Improve IG validation

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateControllerMechanicalVentilation.cpp

ControllerOutdoorAir::miniimumOutdoorAirSchedule has not generally had
an effect on turning off ventilation during off hours.  This is because
ControllerMechanicalVentilation overpowers the minimum oa schedule and
OpenStudio consistently prefers to write the
ControllerMechanicalVentilation.  To rectify this situation, if there is
a ControllerOutdoorAir::minimumOutdoorAirSchedule, then that schedule
will now also be written to the
ControllerMechanicalVentilation::AvailabilitySchedule field when
exporting the idf.  This will disable the mechanical ventilation
controller for periods when minimuOutdoorAirSchedule is zero, thereby
removing its interference.  Fractional schedule values will still not
have this benefit.
[#84418526]
See also https://github.com/NREL/EnergyPlus/issues/4633

Fix min oa schedule complications

---

openstudiocore/src/model/CoolingTowerSingleSpeed.cpp
openstudiocore/src/openstudio_app/Resources/hvaclibrary/hvac_library.osm
openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml

The default constructor and hvac_library ommitted many properties, that
are now included.
[fix #85579792]
fix ##1277

Add single speed tower properties

---

openstudiocore/src/model/AirLoopHVAC.cpp
openstudiocore/src/model/AirTerminalSingleDuctParallelPIUReheat.cpp
openstudiocore/src/model/AirTerminalSingleDuctParallelPIUReheat_Impl.hpp
openstudiocore/src/model/AirTerminalSingleDuctSeriesPIUReheat.cpp
openstudiocore/src/model/AirTerminalSingleDuctSeriesPIUReheat_Impl.hpp
openstudiocore/src/model/test/AirTerminalSingleDuctParallelPIUReheat_GTest.cpp
openstudiocore/src/model/test/AirTerminalSingleDuctSeriesPIUReheat_GTest.cpp

When setting AirLoopHVAC::availabilitySchedule or when adding a new piu
terminal to an existing AirLoopHVAC, make sure the piu fan matches the
system availability schedule.  This is especially useful when night
cycle option is used on the AirLoopHVAC system.
A user can still set the fan availabilty schedule directly to ovrride
this default behavior.
[#84632652]

Adjust PIU fan schedule

---

openstudiocore/src/energyplus/ForwardTranslator.cpp
openstudiocore/src/energyplus/ForwardTranslator.hpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVAC.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACOutdoorAirSystem.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitaryHeatCoolVAVChangeoverBypass.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitaryHeatPumpAirToAir.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
openstudiocore/src/model/AirLoopHVAC.cpp
openstudiocore/src/model/AirLoopHVAC.hpp
openstudiocore/src/model/AirLoopHVAC_Impl.hpp
openstudiocore/src/model/test/AirLoopHVAC_GTest.cpp

Fix the SPM magic so that fans inside unitary systems are accounted for.  This is done during OS -> IDF translation.
Add methods AirLoopHVAC::supplyFan, ::returnFan, ::reliefFan.  These DO NOT account for fans inside compound objects like unitary systems.
https://www.pivotaltracker.com/story/show/86956490

86956490 spm magic

---

openstudiocore/src/model/test/ThermalZone_GTest.cpp

ThermalZone objects are attached to inlet "port lists" and exhaust "port
lists" because they can have multiple connections at those locations.
The ThermalZone class has ThermalZone::exhaustPortList and
ThermalZone::inletPortList that both return the PortList class.
PortList keeps a reference back to the associated ThermalZone and
ThermalZone keeps a reference back to the PortList so that the lookup
is fast in either direction.  User model for issue #447 had a missing
reference from PortList back to ThermalZone.  It is unknown why this
situation occured (model was from version 1.0) but here unit tests are
added to verify that the issue no longer exists.

Add tests for exhaust and inlet port lists

---

CMakeLists.txt
openstudiocore/CMakeLists.txt
openstudiocore/src/openstudio_lib/CMakeLists.txt
openstudiocore/src/openstudio_lib/ResultsTabView.cpp
openstudiocore/src/openstudio_lib/ResultsTabView.hpp
openstudiocore/src/openstudio_lib/ResultsWebEngineView.hpp
openstudiocore/src/openstudio_lib/ResultsWebView.hpp

I'm seeing a 2.8x performance increase for JavaScript, according to the SunSpider benchmark.  This should alleviate #1211 while remaining backwards-compatible.

Switching to QWebEngine if building with Qt >= 5.4

---

openstudiocore/resources/model/OpenStudio.idd

Fixes #1673 
Starting in EnergyPlus 8.2, ZoneHVAC:UnitHeater allows Fan:OnOff.

Allow Fan:OnOff on ZoneHVAC:UnitHeater

---

openstudiocore/src/openstudio_app/Resources/hvaclibrary/hvac_library.osm

Fixes #1605
This solves the issue with CAV and VAV fans with a blank Supply Air Fan Operating Model Schedule. These hvac_library objects will simulate now.
It is currently defaulted to an Always On Discrete schedule, but the user can change a schedule in the GUI where they can not change a Fan Type.

Fix simulation failure for CAV/VAV with no supply fan schedule in hvac library

---

openstudiocore/src/model/ThermalZone.cpp
openstudiocore/src/model/test/ThermalZone_GTest.cpp

A bug was removing the connection to between the original zone (non
clone) and the zone air node during ThermalZone::clone
close #1687

Fix error in ThermalZone::clone

---

openstudiocore/src/utilities/data/Test/TimeSeries_GTest.cpp
openstudiocore/src/utilities/data/TimeSeries.cpp
openstudiocore/src/utilities/sql/SqlFile_Impl.cpp

@axelstudios @macumber This should hopefully fix at least part of the time series issue that came up today. Part of the problem is in SqlFile's timeSeries method. I have changed it to use the new TimeSeries creation behavior, but it still creates "RunPeriod" time series using the detailed ctor rather than the interval ctor. That is not ideal, but is acceptable for now as far as I can tell.

TimeSeries Fix

---

openstudiocore/src/utilities/filetypes/EpwFile.cpp

Fix the EpwFile Linux regex issue by removing the regex usage. It is not clear exactly what the issue was, but using regex here was a bit of overkill.
This will close #1758
This isn't quite ready to go yet. Need to build it on Linux tomorrow and make sure the unit tests pass. But this bug is a blocker, so want to get this in as soon as possible.
@macumber Can you review this?

100880588 Fix EpwFile regex issue by removing regex

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilCoolingDXVariableSpeed.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilCoolingWaterToAirHeatPumpVariableSpeedEquationFit.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingDXMultiSpeed.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingDXVariableSpeed.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingWaterToAirHeatPumpVariableSpeedEquationFit.cpp
openstudiocore/src/model/CoilCoolingDXVariableSpeed.cpp
openstudiocore/src/model/CoilCoolingDXVariableSpeed.hpp
openstudiocore/src/model/CoilCoolingDXVariableSpeed_Impl.hpp
openstudiocore/src/model/CoilCoolingWaterToAirHeatPumpVariableSpeedEquationFit.cpp
openstudiocore/src/model/CoilCoolingWaterToAirHeatPumpVariableSpeedEquationFit.hpp
openstudiocore/src/model/CoilCoolingWaterToAirHeatPumpVariableSpeedEquationFit_Impl.hpp
openstudiocore/src/model/CoilHeatingDXMultiSpeed.cpp
openstudiocore/src/model/CoilHeatingDXMultiSpeed.hpp
openstudiocore/src/model/CoilHeatingDXMultiSpeed_Impl.hpp
openstudiocore/src/model/CoilHeatingDXVariableSpeed.cpp
openstudiocore/src/model/CoilHeatingDXVariableSpeed.hpp
openstudiocore/src/model/CoilHeatingDXVariableSpeed_Impl.hpp
openstudiocore/src/model/CoilHeatingWaterToAirHeatPumpVariableSpeedEquationFit.cpp
openstudiocore/src/model/CoilHeatingWaterToAirHeatPumpVariableSpeedEquationFit.hpp
openstudiocore/src/model/CoilHeatingWaterToAirHeatPumpVariableSpeedEquationFit_Impl.hpp

This converts the new coils from using extensible fields to ModelObjectList instead. This is a better approach.

Convert new coils to using ModelObjectList

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslatePlantComponentTemperatureSource.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslatePlantEquipmentOperationSchemes.cpp

Set default to autosize and add logic to default on an uncontrolled op
scheme unless an operation scheme is explicitly defined.

Fixup PlantComponentTemperatureSource

---

openstudiocore/resources/energyplus/ProposedEnergy+.idd
openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitaryHeatPumpAirToAirMultiSpeed.cpp
openstudiocore/src/model/CoilCoolingDXMultiSpeedStageData.cpp
openstudiocore/src/model/CoilCoolingDXMultiSpeedStageData.hpp

@mbadams5 just a couple of changes to multi speed heating coil. The two commits pretty much say whats going on.
One commit is actually just a convenience addition to Coil *Cooling* multi speed to overload the ctor with a variation that provides curves. This came up in testing of the heating coil and brings the cooling coil inline with convention in other coil types.
The second commit is the important one which adds support for the multi speed heating coil inside the HP unitary. This is the only context indicated by the E+ example files and the only context that I know of where OS will support this coil type.  In other words to use the coil you need this commit.

Coil heating dx multi speed adjustments

---

openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/osversion/VersionTranslator.hpp

Using the version translator check to see if SetpointManagerScheduled
has a value for the control type field and if it doesn't set the value
to "Temperature". This should prevent any possibility of a crash since
this field is required and initialized on object contruction.
close #1747

Make sure that SetpointManagerScheduled has a control type value

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp

OS -> E+ translator would happily translate a partial
ThermostatSetpointDualSetpoint even if one or both schedules are
missing. This causes an EnergyPlus simulation failure. This change makes
it so that a dual setpoint thermostat will only be translated if it has
schedules attached.
This change has become more important with the introduction of
ThermalZone grid view, where there is no longer an explicit on/off
button that effectively allows user control over add/remove
ThermostatSetpointDualSetpoint. A different solution to this problem is
to reprogram grid view to remove the thermostat when the last schedule
is removed, but I think this solution will handle more use cases. It
does come at the expense of perhaps a tiny bit of "magic" but I think it
is acceptable, and will certainly keep …

Fix partial translation of thermostat dual sp

---

openstudiocore/resources/model/OpenStudio.idd

* WaterUseEquipmentDefinition::PeakFlowRate IP units should be gpm
* LoadProfilePlant::PeakFlowRate shoiuld also be gpm
close #1859

Fix IP unit bugs

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateScheduleVariableInterval.cpp
openstudiocore/src/energyplus/Test/ScheduleInterval_GTest.cpp
openstudiocore/src/model/ScheduleInterval.cpp
openstudiocore/src/model/ScheduleVariableInterval.cpp
openstudiocore/src/model/test/ScheduleInterval_GTest.cpp
openstudiocore/src/utilities/filetypes/EpwFile.cpp
openstudiocore/src/utilities/filetypes/EpwFile.hpp

There were actually two related problems causing the failures.
* ScheduleVariableInterval isn't storing enough information to set the start time of a TimeSeries object. The fix for that is to grotesquely assume that the schedule starts at the start of the day. 
* The schedules in the unit tests were not being made correctly and did not start at the start of a day. Correcting the construction errors (the first report times were at the start of a day) fixes the failures. 
Since the original time series in the tests are perfectly legitimate, I have renamed the original tests and kept them. I'll submit an issue to address the poor handling of time series that don't start at the start of a day. 
@macumber I also fixed some formatting errors that I ran across

Fix Failing ScheduleVariableInterval Unit Tests

---

openstudiocore/src/gbxml/ReverseTranslator.cpp

The gbXML reverse translator was assigning the subSurface's construction
to it's parent surface rather than the subSurface itself as noted in issue #1896. This change fixes that issue.

Fix gbXML setConstruction assignment for subSurfaces

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACEquipmentList.cpp
openstudiocore/src/model/PlantEquipmentOperationOutdoorDewpoint.cpp
openstudiocore/src/model/PlantEquipmentOperationOutdoorDewpointDifference.cpp
openstudiocore/src/model/PlantEquipmentOperationOutdoorDryBulb.cpp
openstudiocore/src/model/PlantEquipmentOperationOutdoorDryBulbDifference.cpp
openstudiocore/src/model/PlantEquipmentOperationOutdoorRelativeHumidity.cpp
openstudiocore/src/model/PlantEquipmentOperationOutdoorWetBulbDifference.cpp

OS treats zone ventilation as zone equipment while E+ does not, this is
a fix to avoid writing the zone equipment connections and zone equipment
list when there is only zone ventilation.
close #1919

Fix zone ventilation when it is alone in a zone

---

openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/osversion/VersionTranslator.hpp

For reasons that I don't fully understand, some models between versions
1.9.2 and 1.9.3 bypassed the version translator logic to add the new
required field on some terminals named "Control for Outdoor Air". A new
translator entry between version 1.9.5 and 1.10.0 has been added to make
sure this required field has been set.
close #1985

Fix bug when adding terminal control for oa

---

openstudiocore/src/pat_app/Measures/RadianceMeasure/measure.rb
openstudiocore/src/pat_app/Measures/RadianceMeasure/measure.xml

@macumber, could you give this a spin? It fixes the search order for Radiance stuff, and it reports the Radiance version, that's it. e.g.: 
```[Radiance Measure 2016-02-02 19:38:00 UTC]: Radiance version info: NREL 5.0.a.6 2010.10.15 based on RADIANCE 5.0 Official Release by G. Ward
[Radiance Measure 2016-02-02 19:38:00 UTC]: Radiance binary dir: /usr/local/radiance/bin
[Radiance Measure 2016-02-02 19:38:00 UTC]: Radiance library dir: /usr/local/radiance/lib```
or:
```[Radiance Measure 2016-02-02 19:42:13 UTC]: Radiance version info: RADIANCE 5.0a lastmod 10:24:00 by googs on rgugliel-W7-VM
[Radiance Measure 2016-02-02 19:42:13 UTC]: Radiance binary dir: C:\Users\rgugliel\src\OpenStudio\build\Radiance\bin
[Radiance Measure 2016-02-02 19:42:13 UTC]: Radiance library dir: …
```

Radiance measure paths

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateHeatExchangerFluidToFluid.cpp

If there is no spm on the hx outlet node, then set the
HeatExchangerSetpointNode to the plant outlet node
close #2037 
@jmarrec is this the right change

Fix translation of fluid to fluid HX sepoint nade

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACBaseboardConvectiveWater.cpp
openstudiocore/src/model/CoilHeatingWaterBaseboard.cpp
openstudiocore/src/model/CoilHeatingWaterBaseboard.hpp
openstudiocore/src/model/CoilHeatingWaterBaseboard_Impl.hpp
openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/osversion/VersionTranslator.hpp

std::string heatingDesignCapacityMethod() const;
boost::optional<double> heatingDesignCapacity() const;
bool isHeatingDesignCapacityAutosized() const;
double heatingDesignCapacityPerFloorArea() const;
double fractionofAutosizedHeatingDesignCapacity() const;
close #2233

Add new baseboard fields

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/model/Model.cpp

It was comparing the schedule value to 1.0 instead of 0.0, leading to the creation of a new schedule each time
@kbenne @mbadams5

Fixed alwaysOffDiscrete schedule

---

openstudiocore/src/model/AirConditionerVariableRefrigerantFlow.cpp
openstudiocore/src/model/test/AirConditionerVariableRefrigerantFlow_GTest.cpp

The clone method was leaving behind the curves, and now it is fixed.
close #2226

Fix issue with AirConditionerVariableRefrigerantFlow::clone

---

openstudiocore/src/utilities/core/test/UUID_GTest.cpp
openstudiocore/src/utilities/units/Scale.cpp
openstudiocore/src/utilities/units/Scale.hpp
openstudiocore/src/utilities/units/ScaleFactory.cpp
openstudiocore/src/utilities/units/ScaleFactory.hpp
openstudiocore/src/utilities/units/Unit.cpp
openstudiocore/src/utilities/units/test/IPUnit_GTest.cpp
openstudiocore/src/utilities/units/test/OSQuantityVector_GTest.cpp
openstudiocore/src/utilities/units/test/SIUnit_GTest.cpp
openstudiocore/src/utilities/units/test/ScaleFactory_GTest.cpp
openstudiocore/src/utilities/units/test/Unit_GTest.cpp

Basically, there is some real weirdness when multiplying scales.  If the resulting scale cannot be found, the closest one is returned with an adjustment factor, code was ignoring the adjustment factor because there is no way to use it.  I added more scales, this issue can still occur with other units.

Fixes #2240

---

openstudiocore/src/energyplus/ForwardTranslator.cpp

Just trying to get rid of this fwd translation warning: [openstudio.energyplus.ForwardTranslator] <0> OS_ProgramControl is not currently translated.  Shouldn't be a problem to remove this code since it doesn't get translated to IDF anyway.

Remove creation of ProgramControl object

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
openstudiocore/src/model/CoilHeatingDXVariableSpeed.cpp

This adds:
```
Coil:Cooling:DX:TwoStageWithHumidityControlMode
CoilSystem:Cooling:Water:HeatExchangerAssisted
Coil:Heating:DX:MultiSpeed
Coil:Heating:DX:VariableSpeed
Coil:Heating:Gas:MultiStage
```
as options to AirLoopHVAC:UnitarySystem.
This also fixes a bug in Coil:Heating:DX:VariableSpeed found when testing.
Fixes #2172

Add coils to AirLoopHVAC:UnitarySystem

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
openstudiocore/src/gbxml/MapEnvelope.cpp

Now OpenStudio will generate UnitarySystemPerformanceMultispeed when
a multispeed heating or cooling coil is used.
close #2278

Fix AirLoopHVACUnitarySystem with multispeed coil

---

openstudiocore/src/runmanager/lib/EnergyPlusPreProcessJob.cpp

@macumber I think this is all there is to this. Adding missing meter that was on Electricity Consumption to Electricity Demand.
@asparke2 not sure if this will affect anything you use in OpenStudio standards. The OpenStudio results report doesn't need any changes, this should just show up now.

Fix for Issue #2383

---

openstudiocore/resources/energyplus/ProposedEnergy+.idd

forward translator wasn't setting the name of a Fan:OnOff for ZoneHVAC:UnitVentilator. this *should* fix it.

unit vent fanname

---

openstudiocore/src/resultsviewer/MainWindow.cpp

The issue was that the temp directory where OS puts a copy of the sql
file is actually a symbolic link (this is how the OS sets up the tmp
location). RV has a lot of logic to keep track of open files and
aliases, and some of this logic uses path comparison operations. The
trouble starts when some paths being compared are "canonical" (links
expanded) and others are not expanded. So the solution was just expand
the paths right from the get go. This seemed to only impact files opened
from the cli because it seems the Qt file open dialog already expands
the file paths.
close #2525

Fix problem opening sql in RV from OS App

---

openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateScheduleConstant.cpp
openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateThermostatSetpointDualSetpoint.cpp

All in the title, was currently missing therefore any object would be named with a UUID.

Reverse translate name for ScheduleConstant

---

openstudiocore/resources/energyplus/ProposedEnergy+.idd
openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/CMakeLists.txt
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingGas.cpp
openstudiocore/src/energyplus/Test/CoilHeatingGas_GTest.cpp
openstudiocore/src/model/CoilHeatingGas.cpp
openstudiocore/src/model/test/CoilHeatingGas_GTest.cpp

EnergyPlus recently had an idd change in `Coil:Heating:Fuel` for the fuel type to be `Propane` instead of `PropaneGas`. OpenStudio was still translating to `PropaneGas`. Now, it accepts either in the OS model (warning about the deprecation of `PropaneGas`) and forward translates to `Propane` in EnergyPlus.
Fixes https://github.com/NREL/OpenStudio-BEopt/issues/114
@shorowit

fixing Propane/PropaneGas bug when translating to EnergyPlus

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirTerminalSingleDuctConstantVolumeCooledBeam.cpp

CooledBeamType returns a std::string, not an optional string. See #2192

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslatePlantLoop.cpp
openstudiocore/src/model/PlantLoop.cpp
openstudiocore/src/model/PlantLoop.hpp
openstudiocore/src/model/PlantLoop_Impl.hpp
openstudiocore/src/model/test/PlantLoop_GTest.cpp

Previously there was no way to attribute an availability manager to a plant loop. This made it to where the availability manager wasn't forward translating because it had no parent object. Fixes #2623.
@shorowit @macumber

Plant Loop Availability Manager

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslatePlantLoop.cpp
openstudiocore/src/model/PlantLoop.cpp
openstudiocore/src/model/PlantLoop.hpp
openstudiocore/src/model/PlantLoop_Impl.hpp
openstudiocore/src/model/test/PlantLoop_GTest.cpp
openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml
openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/osversion/VersionTranslator.hpp

This permits the use of PropyleneGlycol and EthyleneGlycol as the fluid type of a `PlantLoop`. It also opens up the ability to set the glycol concentration. The `FluidProperties:Name` and `FluidProperties:GlycolConcentration` idf objects are created on forward translation.
Part of https://github.com/NREL/OpenStudio-BEopt/issues/66
@shorowit

Plant loop fluid concentration

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateUnitarySystemPerformanceMultispeed.cpp

This does a few things to the `UnitarySystemPerformance:Multispeed` forward translation:
1. Allows it to be set on a `AirLoopHVAC:UnitarySystem` that is missing either a heating or cooling system. It appropriately sets the number of speeds to zero in that case now.
2. Allows the use of a `Coil:Heating:Gas:MultiStage` object which is [permitted in EnergyPlus](https://github.com/NREL/EnergyPlus/blob/v8.7.0/src/EnergyPlus/HVACUnitarySystem.cc#L6107) in spite of it not being in the documentation. It correctly forwards the number of speeds. 
3. Rather than error out in OpenStudio, for all other coil types, forwards a number of heating/cooling speeds as 1, which is right for most and will be caught by EnergyPlus error checking if not. This future proofs this a little bit for new kinds of coils. …

UnitarySystemPerformance:Multispeed forward translation

---

openstudiocore/src/model/AirLoopHVAC.cpp

When removing a zone from the air loop, sometimes
neigboring zone hvac equipment on the same zone could
inadvertently be removed. This change corrects the issue.

2787 remove zone from loop

---

openstudiocore/CMakeLists.txt
openstudiocore/src/model/ZoneVentilationDesignFlowRate.cpp
openstudiocore/src/model/ZoneVentilationDesignFlowRate.hpp
openstudiocore/src/model/test/ZoneVentilationDesignFlowRate_GTest.cpp

Fix #2215 (also tested #833 and got it closed by David)
Deprecated the `ZoneVentilationDesignFlowRate::setDesignFlowRateCalculationMethod`, and make it behave like SpaceInfiltrationDesignFlowRate:
if you call setAirChangesperHour(double), it will automatically set the CalculationMethod to "AirChanges/Hour" and put all of other fields as 0.0  (fyi, in SpaceInfiltration, the others are actually optional, and have a default value... )
review assignee: @asparke2 (original #2215 assigned)

Fix #2215 make ZoneVentilationDesignFlowRate behave like SpaceInfiltrationDesignFlowRate (switch the flow rate calc method automatically)

---

developer/msvc/Visualizers/concat_natvis.py
openstudiocore/CMakeLists.txt

Enables usage of [ccache](24a0608839d046bb2c8c239c778b7c6fc56935c0) and the [Ninja Generator](https://ninja-build.org/), and add color output when building with Ninja.
This has been speeding up my build time quite a lot, probably most of it is due to ccache. The first build is a bit slower (builds the cache), but when rebuilding or even switching branches (unless you have an IDD change of course...) it goes much much faster.

Ninja ccache

---

openstudiocore/CMakeLists.txt
openstudiocore/src/energyplus/CMakeLists.txt
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslatePlantEquipmentOperationSchemes.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSizingPlant.cpp
openstudiocore/src/energyplus/Test/PlantEquipmentOperationSchemes_GTest.cpp

Better PlantEquipmentOperation defaults for `HeatExchangerFluidToFluid`, `WaterHeater:Mixed` and `WaterHeater:Stratified`, with Gtest #2749, #2275.
Here's the logic I have used:
**`HeatExchangerFluidToFluid`**:
* Check the `controlType` first, if it's a heating/cooling/dualsetpoint type then assign `ComponentType::HEATING`, `COOLING`, and `BOTH` respectively
* If it's `OperationSchemeModulated` or `OperationSchemeOnOff`, do as before and return BOTH.
* If it's `Uncontrolled`, check the secondary (source) loop supply side (call `plantLoopType`). If no secondary plant loop (weird for a HX...), then `NONE`.
** `WaterHeater:Mixed` and `WaterHeater:Stratified`:**
* If they have a heating capacity (autosized or hardsized > 0): `HEATING`.
* If they don't have a capacity it's a storage tank.
* If …

Fix 2749 2275 plant op logic

---

openstudiocore/CMakeLists.txt
openstudiocore/src/model/AirLoopHVAC.cpp
openstudiocore/src/model/AirTerminalSingleDuctConstantVolumeReheat.cpp
openstudiocore/src/model/AirTerminalSingleDuctParallelPIUReheat.cpp
openstudiocore/src/model/AirTerminalSingleDuctParallelPIUReheat.hpp
openstudiocore/src/model/AirTerminalSingleDuctParallelPIUReheat_Impl.hpp
openstudiocore/src/model/CoilCoolingCooledBeam.cpp
openstudiocore/src/model/CoilCoolingCooledBeam_Impl.hpp
openstudiocore/src/model/CoilCoolingWater.cpp
openstudiocore/src/model/CoilHeatingWater.cpp
openstudiocore/src/model/test/AirLoopHVAC_GTest.cpp
openstudiocore/src/model/test/ZoneHVACPackagedTerminalHeatPump_GTest.cpp

Fix #2022. I realized that the AirTerminal or Coils clone() method isn't called after following the Qt stuff.
Instead AirLoopHVAC::addBranchForZone is called, and in there it's going to rely on the coil 'containingHVACComponent' method. Some missing AirTerminalTypes were uncovered in CoilCoolingWater and CoilHeatingWater, so I implemented that. Also added a containingHVACComponent method to CoilCooledBeam though that was perhaps not necessary due to the need for a check (see next point)
I then realized that ATU:FourPipeInduction is special because it has both a cooling and heating coil.
ATU:CooledBeam is also special because the coilCoolingCooledBeam is a StraightComponent and not a WaterToAirComponent, so I add to implement a check for this in AirLoopHVAC::addBranchForZone.
Wrote Gtests …

Fix 2022 air terminal magic

---

openstudiocore/src/shared_gui_components/OSDoubleEdit.cpp
openstudiocore/src/shared_gui_components/OSQuantityEdit.cpp

Set the QDoubleValidator local for Double and Quantity fields to accept decimal number with a "." separator.
Even my my LC_NUMERIC=ft_FR.UTF-8 I can now edit double/Quantity fields with a "." in there, eg 0.5 is accepted.

Fix #2888 - Enter fractional fields when locale has a comma separator.

---

openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/osversion/VersionTranslator.hpp

Fix #2891: Move the AirLoop/PlantLoop update in a 2.3.0 to 2.3.1 function as it should. Implement a check to assign any existing AvaialbiltiyManager to the newly created AvailabilityManagerAssignementList

Fix #2891 version translation for AVM List

---

openstudiocore/src/model/test/AvailabilityManagerNightCycle_GTest.cpp

Remove calls to deprecated functions in Gtest, apparently causes build to fail on windows because warnings are treated as errors or something
@kbenne

Fix build errors on windows due to avm

---

openstudiocore/src/utilities/bcl/templates/EnergyPlusMeasure/measure.rb
openstudiocore/src/utilities/bcl/templates/EnergyPlusMeasure/tests/energyplus_measure_test.rb
openstudiocore/src/utilities/bcl/templates/ModelMeasure/measure.rb
openstudiocore/src/utilities/bcl/templates/ModelMeasure/tests/model_measure_test.rb
openstudiocore/src/utilities/bcl/templates/ReportingMeasure/measure.rb
openstudiocore/src/utilities/bcl/templates/ReportingMeasure/tests/reporting_measure_test.rb

Fixes issue #2656 had to create workflow on the fly to create runner.
Also removed 1x path for reporting measure test. Note: Measure made
based on these templates should not be back versioned in measure.xml to
1.x version of OpenStudio.

Removing Ruleset from measure and measure test templates

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEnergyManagementSystemActuator.cpp
openstudiocore/src/energyplus/Test/EMS_GTest.cpp

* One test ForwardTranslatorWeatherActuator_EMS was failing because setting an actuator to a WeatherFile which doesn't have a name:  a tiny thing introduced in Brian's PR [here](https://github.com/NREL/OpenStudio/pull/2890/files#diff-d6cc26d9e8d081a74e006bd8ed735047R80). Just need to check whether the actuated component is "Site" or "Weather File" before you check if it has a name in ForwardTranslator
* Behavior at one point was to automatically rename var names with spaces to an underscore, now it throws in the constructor if a name with space is supplied, so need to adjust the FT tests accordingly (passing "glob var" is no longer accepted, so need to pass "glob_var" directly)
* The reverse translator tests were failing because they load the IDF file created by the previous …

Fix failing ems tests

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateBoilerHotWater.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateBoilerSteam.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateChillerElectricEIR.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateWaterHeaterMixed.cpp
openstudiocore/src/model/BoilerSteam.cpp
openstudiocore/src/model/BoilerSteam.hpp
openstudiocore/src/model/BoilerSteam_Impl.hpp
openstudiocore/src/model/ChillerElectricEIR.cpp
openstudiocore/src/model/ChillerElectricEIR.hpp
openstudiocore/src/model/ChillerElectricEIR_Impl.hpp
openstudiocore/src/model/ScheduleTypeRegistry.cpp
openstudiocore/src/model/WaterHeaterMixed.cpp
openstudiocore/src/model/WaterHeaterMixed.hpp
openstudiocore/src/model/WaterHeaterMixed_Impl.hpp
openstudiocore/src/model/test/WaterHeaterMixed_GTest.cpp
openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml
openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/osversion/VersionTranslator.hpp

I noticed in @JasonGlazer 's Leed reporting measure, there are notes about missing "End Use Subcategory" Fields (see [here](https://github.com/JasonGlazer/LEEDreport/blob/master/apply_end_use_subcategory/resources/End-Use%20Subcategory%20OpenStudio%20Measure%20Design%20Doc-rev01.pdf).
The cooling towers already had them. I added it for WaterHeater:Mixed, Boiler:HotWater and Boiler:Steam and Chiller:Electric:EIR, and that should be all of it now.
Wrote version translation to hardset these fields to "General".
I added the fields in between (end use subcat is the last in IDD) where there were any, but I only implemented setters, getters and forward translation for the WaterHeater;Mixed new fields Source Side Flow Control Mode and IndirectAlternateSetpointTemperatureSchedule.
For …

Add end use sub categories where missing

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateElectricLoadCenterDistribution.cpp
openstudiocore/src/model/ElectricLoadCenterDistribution.cpp

I think it was just a mistake on my part, I forgot to uncomment this section, which I think I wrote before I actually implement the StorageConv object. Found this while writing a regression test for storage objects.
Also found a random copy/paste error in the IDD. Note that the copy/paste error has no actual effect aside that it isn't pretty when you look at it, because you need to use addLoadRange anyways (and not setWetBulbTemperature.....etc)

Storage Converter isn't translated for FacilityDemandLeveling while required

---

openstudiocore/src/install_utility/main.cpp

On Mac, if the /usr/bin/openstudio link already exists,
perhaps from a previous version, then the attempt to
make a new link will fail.
Remove the old stale link before making the new link.
close #2428

Update link to openstudio cli

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateScheduleTypeLimits.cpp

Fix for #3075 
Still unsure whether `ProposedEnergy+.idd` should match the official E+ `Energy+.idd` (see comment on #3075 directly)

Handle all extra keys that aren't in EnergyPlus's idd `Energy+.idd`

---

openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/osversion/VersionTranslator.hpp

Fix #3084 and NREL/OpenStudio-resources#43 (only the `afn_single_zone_nv.osm` portion of that issue)
Changelog:
* 2.4.3 was removed from `m_startVersions` -> add it back. 
* Handle 2.4.3 to 2.5.0 version translation for `OS:AirflowNetworkZone` which has a newly inserted `Name` field right after the handle. Shift all fields by 1, and for the 'Name', get the attached thermal zone name and name it like `"Airflow Network Zone " + _zone->nameString());`
Could you review @evanweaver please?
----
FYI this new field was added in 18387eb0be4ff41a5d5e0ab3d28060ba817d80cb by @jasondegraw (exactly [here](https://github.com/NREL/OpenStudio/commit/18387eb0be4ff41a5d5e0ab3d28060ba817d80cb#diff-20dc466cd26aed8488ee9b0bb0d5ce9aR28947))
----
Note that the official 2.5.0 build doesn't have this change and …

Fix #3084 and NREL/OpenStudio-resources#43

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp
openstudiocore/src/energyplus/Test/ForwardTranslator_GTest.cpp
openstudiocore/src/energyplus/Test/SurfacePropertyConvectionCoefficients.cpp
openstudiocore/src/model/test/AirflowNetworkDuctViewFactors_GTest.cpp

This is a very minor change.
The Model/EnergyPlusFixture redirects LogMessages to a log file for a reason! Three tests  were responsible for an output that was unreadable, because the problem is that when you run all GTests, it'll affect ALL subsequent tests.

Turn Off standardOutLogger in Individual tests

---

openstudiocore/CMakeLists.txt

Fix #2974 
Trusty (14.04) has libwxgtk3.0-0, all subsequent ubuntu versions including Xenial (16.04) use libwxgtk3.0-0v5.
So I set the CPACK_DEBIAN_PACKAGE_DEPENDS to include either of these two so it should work on 14.04 and 16.04 (I tested that it fixes it in 16.04 at least)

Fix #2974 - libwxgtk dependencies on Linux

---

openstudiocore/src/openstudio_lib/GridItem.cpp

This PR implements an extra check to avoid a hard crash as reported in #3116. You can't `pop_back()` on an empty `std::vector` so it checks for that.
The only thing I didn't manage to do is to actually remove said orphaned object. I'm trying to call `ModelObject_Impl::remove()` directly and not the actual component's remove, which, in case of a `Node` for eg will check if `isRemovable()` - which returns False since it does have a Loop.
I left a TODO: 
https://github.com/NREL/OpenStudio/compare/develop...jmarrec:Fix_3116_Catch_Orphaned_Components?expand=1#diff-72d558d6b647a3c0057d728d2739b681R1201
With this fix, at least the Loop loads fine in OS App for review, a warning is issued to the user (always a good thing), and the model should run fine since it's going to get caught in Forward …

Fix 3116 catch orphaned components

---

openstudiocore/src/openstudio_app/Resources/default/hvac_library.osm

This small pull request just adds `SetpointManager:SingleZone:Humidity:Minimum` to the hvac_library.osm.
Fix #3130

Fix #3130 - Add SPM Single Zone Humidity Minimum to hvac_library

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp

I forgot to handle that when I made #2813. If you put a Cooling schedule only on a zone (no heating) that has equipment, you end up with a Thermostat:SingleCooling BUT the ZoneControl:Thermostat still has a ControlTypeScheduleName with a value of 4, which is wrong (4 = DualSetpoint)

Fix thermostat schedule control value

---

openstudiocore/src/openstudio_app/OpenStudioApp.cpp
openstudiocore/src/openstudio_app/install_operations.qs
openstudiocore/src/utilities/core/Path.cpp

Fix #2832 - Cannot Open File Path with spaces on windows
Basically just quote the filepath so that if there are spaces, it's still captured as a single argument and not several.
If I double click on `C:\Users\julien\2832_CannotLoadSpaces\a file with spaces.osm`, here are the content of argv:
**Before**:
```
arg 0: C:\Users\julien\Software\Others\OS-build\Products\Debug\OpenStudioApp.exe
arg 1: C:\Users\julien\2832_CannotLoadSpaces\a
arg 2: file
arg 3: with
arg 4: spaces.osm
```
**After:** It is correctly identified as a single argument.
```
arg 0: C:\openstudio-2.6.1/bin/OpenStudioApp.exe
arg 1: C:\Users\julien\2832_CannotLoadSpaces\a file with spaces.osm
```

Fix #2832  (and #2567) - OS App Cannot Open File Path with spaces or special characters on windows

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/model/FanConstantVolume.cpp
openstudiocore/src/model/FanConstantVolume.hpp
openstudiocore/src/model/FanConstantVolume_Impl.hpp
openstudiocore/src/model/FanOnOff.cpp
openstudiocore/src/model/FanOnOff.hpp
openstudiocore/src/model/FanOnOff_Impl.hpp
openstudiocore/src/model/FanVariableVolume.cpp
openstudiocore/src/model/FanVariableVolume.hpp
openstudiocore/src/model/FanVariableVolume_Impl.hpp
openstudiocore/src/model/FanZoneExhaust.cpp
openstudiocore/src/model/FanZoneExhaust.hpp
openstudiocore/src/model/FanZoneExhaust_Impl.hpp
openstudiocore/src/model/test/FanOnOff_GTest.cpp

Fix #2059 - change Fan Efficiency field to Fan Total Efficiency.
Changelog:
* Change Fan Efficiency to Fan Total Efficiency in IDD (which now matches E+)
* Rename the private (_Impl) methods to `fanTotalEfficiency`
* Public interface now that `fanTotalEfficiency` and the old `fanEfficiency` that forwards to the Impl one.
Note: I was told to not explicitly deprecate the old `fanEfficiency` methods (that is put an `OS_DEPRECATED` in front)
Original issue assignee: @kbenne. Could you review this one please?

Fix #2059 - change Fan Efficiency field to Fan Total Efficiency

---

openstudiocore/resources/model/OpenStudio.idd

Fix #2343.
I added a `\ip-units gal/min` for LowTemperatureRadiant:ConstantFlow and found another occurrence in Refrigeration:SecondarySystem.
**Warning: IDDChange**
@macumber Could you review this one? (nothing to review really...)

Fix 2343 wrong ip units for LowTemperature Pump Head

---

openstudiocore/src/shared_gui_components/OSConcepts.hpp

Fix #2814 (and #2176)
setString doesn't enforce casing to match the possible `\key` for a `\type choice` IDDfield. Most DDY files have Humdity Indicating Type set as `Wetbulb` whereas the IDD has `WetBulb` (capital "B"); so it can't find it, and either displays a blank string or if in Debug hits an OS_ASSERT and crash.
Changelog: In OSComboBox2, if you can't find it in the possible keys, then match case insentitive, and return the appropriately-cased value.
Note: I've been explicitly told to handle it on the OS App side only, rather than enforce casing when calling setString on a `\type choice` field.
----
Original issue assignee: @kbenne. Could you review this one please?

Fix #2814 and #2176: Problem with Humidity Indicating type

---

openstudiocore/src/openstudio_lib/GridItem.cpp

Fix #1717 - wrong fan direction in Outdoor Air Supply
Before:
After:
Original issue assignee: @kbenne. Could you review this one please?

Fix #1717 - wrong fan direction in Outdoor Air Supply

---

openstudiocore/src/openstudio_lib/VRFGraphicsItems.cpp

Fix for #2555.
I change the thermalzone font size from 25 to 16. I don't know if that's enough to close #2555 or not, or if we should consider making the whole view larger.
Before:
After
Original issue assignee: @kbenne, though isn't really HVAC related, so perhaps @macumber should take it?
Can one of you two review this one please?

Fix #2555 - vrf font size too large

---

openstudiocore/resources/model/OpenStudio.idd

Fix #2057: was just missing an `\ip-units gal/min` flag.
Warning: **IDDChange** (so full recompilation needed...)
Original issue assignee: @kbenne. Could you review this one please? (there's really nothing to review)

Fix #2057 wrong ip unit ctrl water coil

---

openstudiocore/src/openstudio_lib/ModelObjectListView.cpp

I had addressed some of the other concerns of #2274 at end of 2017 (see [here](https://github.com/NREL/OpenStudio/issues/2274#issuecomment-334411783)) but after a brief look I didn't get why the tank still couldn't get dragged
Turns out it's because it checks if its part of another component: currently if any component is contained in a ZoneHVACComp or HVACComp, it's not shown in model list. So I just handled this special case.
*Note: this will have the side effect of allowing the HPWH Tanks from the hvac_library to be dragged, but it's not a big deal since this won't drag the HeatPump and other associated components (DX coil, fan, etc).
And this behavior is existing with the fans contained in some of the ZoneHVACComp etc.*
----
After adding an HPWH:WrappedCondenser to one of my thermal …

Fix #2274 Cannot drag HPWH tank to plantloop from my model.

---

openstudiocore/src/openstudio_app/main.cpp

Allow using an environment variable `OPENSTUDIO_APPLICATION_LOGFILE_PATH` to trigger logging message to a file (helpful especially on macOS...)
On unix, don't do it in bash_profile obviously:
* macOS: see [this answer](https://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite)
* ubuntu:  /etc/environment

OS App - Env variable to trigger logging to file

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirTerminalSingleDuctVAVNoReheat.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirTerminalSingleDuctVAVReheat.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSizingSystem.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneHVACWaterToAirHeatPump.cpp
openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateAirTerminalSingleDuctVAVNoReheat.cpp
openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateAirTerminalSingleDuctVAVReheat.cpp
openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateSizingSystem.cpp
openstudiocore/src/model/AirTerminalSingleDuctVAVNoReheat.cpp
openstudiocore/src/model/AirTerminalSingleDuctVAVNoReheat.hpp
openstudiocore/src/model/AirTerminalSingleDuctVAVNoReheat_Impl.hpp
openstudiocore/src/model/AirTerminalSingleDuctVAVReheat.cpp
openstudiocore/src/model/AirTerminalSingleDuctVAVReheat.hpp
openstudiocore/src/model/AirTerminalSingleDuctVAVReheat_Impl.hpp
openstudiocore/src/model/AirflowNetworkEquivalentDuct_Impl.hpp
openstudiocore/src/model/HVACTemplates.cpp
openstudiocore/src/model/ModelObject.hpp
openstudiocore/src/model/SizingSystem.cpp
openstudiocore/src/model/SizingSystem.hpp
openstudiocore/src/model/SizingSystem_Impl.hpp
openstudiocore/src/model/ZoneHVACWaterToAirHeatPump.cpp
openstudiocore/src/model/ZoneHVACWaterToAirHeatPump.hpp
openstudiocore/src/model/ZoneHVACWaterToAirHeatPump_Impl.hpp
openstudiocore/src/model/test/AirTerminalSingleDuctVAVNoReheat_GTest.cpp
openstudiocore/src/model/test/ZoneHVACWaterToAirHeatPump_GTest.cpp
openstudiocore/src/sdd/MapHVAC.cpp

**Warning:** this PR breaks backward compatibility in the API, because fields that weren't autosizable used to have a getter that returned a double, and now it must return boost::optional<double>.
----
## Changelog:
* Fix #2718 : `Sizing:System` "Minimum System Air Flow Ratio" is renamed to "Central Heating Maximum System Air Flow Ratio" to match E+, and becomes autosizable. 
* Fix #2625:  `AirTerminalSingleDuctVAVReheat` and `AirTerminalSingleDuctVAVNoReheat` have two fields - Constant Minimum Air Flow Fraction and Fixed Minimum Air Flow Rate that become autosizable
* All new autosizable fields go their related SQL querying methods (tested with the OpenStudio-resources autosizing_rb test) and added to the `autosize()` and `applySizingValues()`
* …

Fix #2718 #2625 fields that became autosizable

---

openstudiocore/src/openstudio_lib/ResultsTabView.cpp

Fix #3019 - Crash happens when going to results tab when you do NOT have a companion folder
Just need to check if the directory actually exists first before passing it to directory_iterator. I confirmed that it now works on macOS High Sierra with that fix.

Fix #3019 - Crash happens when going to results tab when you do NOT have a companion folder

---

openstudiocore/src/openstudio_lib/FacilityShadingGridView.cpp

Fix #1797 - Don't show 'Space' shading on the Facility 'Shading' subtab
Ensure that we don't display Space-level shading on the Facility 'Shading' subtab. Made it disappear on three locations:
* Shading groups whcih shadingSurfaceType() == 'Space' are not display
* Shading Surface Type Filter only proposes 'Site' and 'Building'
* The 'Type' dropdown only proposes 'Site' and 'Building'

Fix #1797 - Don't show 'Space' shading on the Facility 'Shading' subtab

---

openstudiocore/src/openstudio_lib/ThermalZonesGridView.cpp

Fix #78 - Add rendering color picker on ThermalZones tab
I put it in the first column to match the location on the 'SpaceType' tab:
[image](https://user-images.githubusercontent.com/5479063/44572462-2b5f7d00-a784-11e8-8e1d-813a181b390a.png)
Review assignee: @macumber  (it's really trivial)

Fix #78 - Add rendering color picker on ThermalZones tab

---

openstudiocore/src/openstudio_lib/MainRightColumnController.cpp
openstudiocore/src/openstudio_lib/MaterialsView.cpp

Relates to #1329 and #1697.
Problem is that the ThermochromicGlazing isn't wrapped correctly (or at least fully) in the SDK. Until it is, we comment it out of the OS App.
What I chose to do is to just not display Thermochromic in MainRightColumn nor under the Materials tab.
That was the minimal amount of commenting out that would just not display it to the user, and it would be really easy to re-add it.
**If you want me to take it out completely** (including removing `WindowMaterialGlazingGroupThermochromicInspectorView` from CMakeLists.txt), **please let me know and I will**

#1329 - Comment out Thermochromic glazing in OS App

---

openstudiocore/src/openstudio_lib/EMSInspectorView.cpp
openstudiocore/src/openstudio_lib/OSDocument.cpp
openstudiocore/src/openstudio_lib/SchedulesView.cpp
openstudiocore/src/openstudio_lib/VRFController.cpp
openstudiocore/src/shared_gui_components/OSGridView.cpp
openstudiocore/src/shared_gui_components/OSViewSwitcher.cpp

Fix #2934 - Fix qt warnings in app
Removed all std::cout statements I could find, and fixed the Qt warning about no placeholder in window title (see Qt docs about [windowModified](https://doc.qt.io/qt-5/qwidget.html#windowModified-prop)).
There aren't any warnings in Release mode anymore.
In Debug mode, there's this Qt warning that will keep poping up 16 times each time you switch to a tab that has an OSGridController in it:
```
Warning: QLayout: Attempting to add QLayout "" to openstudio::OSGridView "", which already has a layout ((null):0, (null))
```
I haven't been able to pinpoint the root cause of this one. Refer to #2934 for more info.

Fix #2934 - Fix qt warnings in app

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp
openstudiocore/src/model/ThermalZone.cpp

Fix #749 - Warn when mismatched "Part of Total Floor Area" flags in zone
I initially put code in ForwardTranslateThermalZone.cpp, then I remembered that prior to getting there, thermalZone.combineSpaces() is called first, so the zone has zero or one space only. So I moved the message into that method, and made it an Info rather than a Warning since it's doing the right thing (see my comment https://github.com/NREL/OpenStudio/issues/749#issuecomment-416897214 for more info)

Fix #749 - Warn when mismatched "Part of Total Floor Area" flags in zone

---

openstudiocore/src/model/FileOperations.cpp
openstudiocore/src/model/Model.cpp
openstudiocore/src/openstudio_lib/ApplyMeasureNowDialog.cpp
openstudiocore/src/openstudio_lib/OSDocument.cpp
openstudiocore/src/openstudio_lib/ResultsTabView.cpp
openstudiocore/src/openstudio_lib/RunTabView.cpp
openstudiocore/src/openstudio_lib/RunTabView.hpp
openstudiocore/src/shared_gui_components/MeasureManager.cpp
openstudiocore/src/shared_gui_components/WorkflowController.cpp
openstudiocore/src/utilities/core/PathHelpers.cpp
openstudiocore/src/utilities/core/PathHelpers.hpp
openstudiocore/src/utilities/core/test/Path_GTest.cpp
openstudiocore/src/utilities/filetypes/WorkflowJSON.cpp

Fix #3249 - path problems
More info on the issue.
Changelog:
* Do not use `.stem()` when trying to get the last level directory name because it won't work properly if you have a `.` in there, instead use `.filename()`
* Created two functions in PathHelpers for clarity (and easier to change later if need be / add checks): `getCompanionFolder(path& osmPath)` and `getLastLevelDirectoryName(path& directory)`
* Note that we could include some tests in there, but I didn't because of speed (we assume we know when we pass an OSM file or a directory to the appropriate functions)
* Made various locations where file stuff is happening use these two functions
Warning: Please pay close attention to 8c6b8ed95a366fc7ca654f2bdb2891348b01fafc where I think I caught a problem and fixed it, thanks!
Review …

Fix #3249 - path problems

---

openstudiocore/src/openstudio_lib/DesignDayGridView.cpp
openstudiocore/src/openstudio_lib/SpacesInteriorPartitionsGridView.cpp
openstudiocore/src/openstudio_lib/SpacesSpacesGridView.cpp
openstudiocore/src/openstudio_lib/ThermalZonesGridView.cpp
openstudiocore/src/shared_gui_components/OSCheckBox.cpp
openstudiocore/src/shared_gui_components/OSCheckBox.hpp
openstudiocore/src/shared_gui_components/OSConcepts.hpp
openstudiocore/src/shared_gui_components/OSGridController.cpp
openstudiocore/src/shared_gui_components/OSGridController.hpp

Fix #2712 which was specially about the "Turn on Ideal Air Loads", and do that for all checkboxes actually
For all checkboxes except the "All" column, the "Apply to Selected" button is enabled and functional (provided you do pass a Heading that has a `t_showColumnButton=true` which I did for all checkboxes now)
When you select such a checkbox, it becomes yellow to help you figure out one which you clicked.
here's a gif showing the UX:

Fix #2712 Enable Apply to selected for checkboxes

---

openstudiocore/src/openstudio_lib/ApplyMeasureNowDialog.cpp

Fix #2600: was overriding setNumWarnings with infos.size()
Review assignee: @macumber (it's just one trivial line.)

Fix #2600: Apply Measure Now incorrectly reporting warning message count with data from info messages

---

openstudiocore/src/openstudio_lib/OSDocument.cpp
openstudiocore/src/openstudio_lib/OSDropZone.cpp

Fix #2000 - Allow dropping BCL construction on Surface subtab
I implemented the fix in `OSDropZone2::dropEvent` where I check if it's a BCL thing and then load it appropriately, else continue to call `OSDocument::getModelObject `.
I'm not sure if this fix shouldn't be in `OSDocument::getModelObject` instead...

Fix #2000 - Allow dropping BCL construction on Surface subtab

---

openstudiocore/src/openstudio_app/OpenStudioApp.cpp
openstudiocore/src/openstudio_lib/MainMenu.cpp

Fix #1554 - Always enable Revert to Saved 
Changelog:
* Always Enable Revert to Saved: if we think the model is dirty, I just display an asterisk next to "Revert to Saved" (which may not be needed since the MainWindow title also does)
* Per @macumber's comment on the issue, Revert to Saved now will create a brand new model when it was never saved.
Question here is whether after this dialog box, we should also show the standard one (I think there's some value there).

Fix #1554 - Always enable Revert to Saved 

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateTableMultiVariableLookup.cpp
openstudiocore/src/model/ModelCore.i
openstudiocore/src/model/ModelResources.i
openstudiocore/src/model/ScheduleFile_Impl.hpp
openstudiocore/src/model/TableMultiVariableLookup.cpp
openstudiocore/src/model/TableMultiVariableLookup.hpp
openstudiocore/src/model/TableMultiVariableLookup_Impl.hpp
openstudiocore/src/model/test/TableMultiVariableLookup_GTest.cpp

Related to discussion with @macumber  in #3223 
```ruby
m = OpenStudio::Model::Model.new
capModFuncOfWaterFlow = OpenStudio::Model::TableMultiVariableLookup.new(m, 1)
capModFuncOfWaterFlow.setName("CapModFuncOfWaterFlow")
capModFuncOfWaterFlow.setCurveType("Quadratic")
capModFuncOfWaterFlow.setInterpolationMethod("EvaluateCurveToLimits")
capModFuncOfWaterFlow.setMinimumValueofX1(0)
capModFuncOfWaterFlow.setMaximumValueofX1(1.33)
capModFuncOfWaterFlow.setMinimumTableOutput(0.0)
capModFuncOfWaterFlow.setMaximumTableOutput(1.04)
capModFuncOfWaterFlow.setInputUnitTypeforX1("Dimensionless")
capModFuncOfWaterFlow.setOutputUnitType("Dimensionless")
capModFuncOfWaterFlow.addPoint(0.0, 0.0)
capModFuncOfWaterFlow.addPoint(0.05, 0.001)
capModFuncOfWaterFlow.addPoint(0.33333, 0.71) …
```

Handle TableMultiVariableLookup::points

---

dependencies/ruby/Gemfile
dependencies/ruby/Gemfile.lock
openstudiocore/CMakeLists.txt

Updates openstudio-standards to 0.2.4, which fixed bugs in HVAC system sizing, DOE prototype geometries, and other things.
@macumber I built and tested on Windows using OS App.

Updates openstudio-standards to 0.2.4

---

openstudiocore/src/openstudio_lib/InspectorView.cpp
openstudiocore/src/openstudio_lib/LibraryTabWidget.cpp
openstudiocore/src/openstudio_lib/LibraryTabWidget.hpp

Fix #1877 non functional link subtab for HVACComponents
Changelog:
* Added `LibraryTabWidget::hideTab` function to hide the tab by hiding the link button and handle the currentIndex. Adapted from [HorizontalTabWidget::hideTab](https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/openstudio_lib/HorizontalTabWidget.cpp#L225)
* For each component, instead of calling `LoopChooserView::layoutModelObject` with an empty optional, I call `hideTab`
eg: PTAC with an electric coil:
PTAC with a HW coil:
One thing I need to mention is that if you have a cooling coil (3rd tab) and no heating coil (2nd tab) it'll look like this, which I don't see as a problem:

Fix #1877 non functional link subtab for HVACComponents

---

openstudiocore/src/openstudio_lib/HVACSystemsController.cpp
openstudiocore/src/openstudio_lib/HVACSystemsController.hpp

Fix #535 - update system combo box on loop name change
I used debug message to make sure that I don't end up triggering the same slots repeatedly (it proved useful: I actually was initially, forgot to add `!` to a bool check, but I fixed it!)
Demo:
Review Assignee: @macumber

Fix #535 - update system combo box on loop name change

---

openstudiocore/src/model/GeneratorFuelSupply.cpp
openstudiocore/src/model/test/GeneratorFuelSupply_GTest.cpp

GeneratorFuelSupply: Change Ctor defaults to avoid E+ error with LiquidGeneric
Cf: https://github.com/NREL/EnergyPlus/issues/6998

GeneratorFuelSupply: Change Ctor defaults to avoid E+ error with LiquidGeneric

---

dependencies/ruby/Gemfile
dependencies/ruby/Gemfile.lock
openstudiocore/CMakeLists.txt

Updates openstudio-standards gem to 0.2.6 to make the gems compatible with OpenStudio 2.7.0 API changes.

Updates openstudio-standards to 0.2.6

---

openstudiocore/src/model/ModelCore.i

all EMS gtests pass
test for Ruby swig issues pass in this PR to OS-resources:
https://github.com/NREL/OpenStudio-resources/pull/62

fix 3336 EMS metered output variable program swig hookup

---

openstudiocore/src/model/AirLoopHVAC.cpp
openstudiocore/src/model/AirLoopHVAC.hpp
openstudiocore/src/model/AirLoopHVAC_Impl.hpp
openstudiocore/src/model/SetpointManager.cpp
openstudiocore/src/model/SetpointManager.hpp
openstudiocore/src/model/SetpointManagerFollowGroundTemperature.cpp
openstudiocore/src/model/SetpointManagerFollowGroundTemperature_Impl.hpp
openstudiocore/src/model/SetpointManagerFollowOutdoorAirTemperature.cpp
openstudiocore/src/model/SetpointManagerFollowOutdoorAirTemperature_Impl.hpp
openstudiocore/src/model/SetpointManagerFollowSystemNodeTemperature.cpp
openstudiocore/src/model/SetpointManagerFollowSystemNodeTemperature_Impl.hpp
openstudiocore/src/model/SetpointManagerOutdoorAirReset.cpp
openstudiocore/src/model/SetpointManagerOutdoorAirReset_Impl.hpp
openstudiocore/src/model/SetpointManagerScheduled.cpp
openstudiocore/src/model/SetpointManagerScheduledDualSetpoint.cpp
openstudiocore/src/model/SetpointManagerScheduledDualSetpoint_Impl.hpp
openstudiocore/src/model/SetpointManagerScheduled_Impl.hpp
openstudiocore/src/model/SetpointManager_Impl.hpp
openstudiocore/src/openstudio_lib/GridItem.cpp

Fix #1465 and Fix #2220 
Changelog:
* Previous behavior was to only draw (and make removable) the SPMs with a `controlVariable`  that is "Temperature", now allows the other too (=the humidity ones basically)
* Implemented the `AirLoopHVAC::outdoorAirNode` and `AirLoopHVAC::returnAirNode`: since 2011 they were just throwing a "Not implemented" currently.
* Made  `AirLoopHVAC::mixedAirNode` and `AirLoopHVAC::reliefAirNode` const (const-correctness)
* `SetpointManager_Impl::addToNode` now doesn't allow SPMs to be placed on the `reliefAirNode` nor the `outdoorAirNode` of an AirLoopHVACOutdoorAirSYstem
* All SPMs that are allowed on a plantLoop now can only be placed on the supply side (I disallowed placing them on the demand side of a PlantLoop)
Original issue assignee: @kbenne. Could you …

Fix 1465: Can't remove some SPMs via GUI because icons don't show

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateShadingControl.cpp

The Daylighting control object is not required for the WindowShadingControl object. See AirflowWindowsAndBetweenGlassBlinds.idf example file, for example. We get lots of errors because of this but simulations run fine.
cc @joseph-robertson

Change daylighting error to a warning

---

openstudiocore/src/utilities/bcl/BCLMeasure.cpp
openstudiocore/src/utilities/core/PathHelpers.cpp
openstudiocore/src/utilities/core/RubyException.hpp
openstudiocore/src/utilities/core/URLHelpers.cpp
openstudiocore/src/utilities/core/test/Path_GTest.cpp
openstudiocore/src/utilities/sql/Test/SqlFile_GTest.cpp

Replaced with `boost::regex`.
I think I caught every location that isn't OS App related
```bash
$ cd OpenStudio/openstudiocore
$ grep -Rl "QReg[uE]" 
model_editor/InspectorGadget.cpp
model_editor/IGLineEdit.cpp
model_editor/IGPrecisionDialog.cpp
openstudio_lib/FacilityShadingGridView.cpp
openstudio_lib/FacilityStoriesGridView.cpp
openstudio_lib/ResultsTabView.cpp
openstudio_lib/SpacesSubtabGridView.cpp
shared_gui_components/EditView.cpp
```
Note: I left two "TODO" inside BCLMeasure.cpp because boost::replace_all isn't working in my current setting (I use a much newer GCC than the one that compiled boost), but it should work fine after update_depends is merged in (on my system, I have a test project with boost 1.68 compiled with GCC-7 and this works)

Remove QRegExp and QRegularExpression

---

openstudiocore/src/cli/RubyInterpreter.hpp
openstudiocore/src/model/FileOperations.cpp
openstudiocore/src/openstudio_lib/OSDocument.cpp
openstudiocore/src/radiance/ForwardTranslator.cpp
openstudiocore/src/utilities/bcl/BCLMeasure.cpp
openstudiocore/src/utilities/bcl/LocalBCL.cpp
openstudiocore/src/utilities/bcl/LocalBCL.hpp
openstudiocore/src/utilities/bcl/RemoteBCL.cpp
openstudiocore/src/utilities/bcl/test/BCLMeasure_GTest.cpp
openstudiocore/src/utilities/bcl/test/BCL_GTest.cpp
openstudiocore/src/utilities/core/Filesystem.hpp
openstudiocore/src/utilities/core/FilesystemHelpers.cpp
openstudiocore/src/utilities/core/FilesystemHelpers.hpp
openstudiocore/src/utilities/core/Path.cpp
openstudiocore/src/utilities/core/RubyInterpreter.hpp
openstudiocore/src/utilities/core/UnzipFile.cpp

While removing these two dependencies I also removed dead code that relied on them (as opposed to spending the time updating code that isn't used) and cleaned up some redundant code.
* `QTemporaryFile` is a clean extraction
* `QDir` mostly effected BCL.
* It's possible we'll get merge conflicts with code that is removing `QSql` because I took the opportunity to clean up some redundant code. If this happens I can hopefully sort out the merge conflicts easily.

Remove QTemporaryFile and QDir

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateShadingControl.cpp

Similar to [this shading control daylighting PR](https://github.com/NREL/OpenStudio/pull/3361), the shading control error about spanning multiple controls should be reduced to a warning. It's fine to have a shading control span multiple thermal zones depending on its controls. We are successfully using this configuration in E+ without issues.

Reduce shading control FT error to warn

---

openstudiocore/src/model/FileOperations.cpp
openstudiocore/src/model/FileOperations.hpp
openstudiocore/src/openstudio_app/OpenStudioApp.cpp
openstudiocore/src/openstudio_lib/GeometryEditorView.cpp
openstudiocore/src/openstudio_lib/GeometryPreviewView.cpp
openstudiocore/src/openstudio_lib/ResultsTabView.cpp
openstudiocore/src/openstudio_lib/openstudiolib.qss
openstudiocore/src/utilities/bcl/BCLXML.cpp
openstudiocore/src/utilities/core/Filesystem.hpp
openstudiocore/src/utilities/core/FilesystemHelpers.cpp

**Status: IN PROGRESS** (so that I can track progress)
**Changelog:**
* Before:
* After: 
* Problem is that unlike `QDir` equivalent, `boost::filesystem::canonical()` used at [FileOperations.cpp#L92](https://github.com/NREL/OpenStudio/blob/df94a2183ddde851fad7e43f2dc0ef219d97e16a/openstudiocore/src/model/FileOperations.cpp#L92) actually imposes that the path exists, when the destination directory (=companion folder) could actually not exist until created. 
* Replace this with `boost::filesystem::weakly_canonical()`
* This is due to new parsing of BCXML: whether the `error` key is present or not `m_error` is initialized (to an empty string if the key was missing). Adjsuted to check for presence of key before

Fix OS App Issues with develop3

---

.gitignore

I built in `OpenStudio/openstudiocore/build` since it felt more natural, and it's annoying to have thousands of untracked files.

Update gitignore to ignore build folders throughout

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/model/DefaultConstructionSet.cpp
openstudiocore/src/model/DefaultConstructionSet.hpp
openstudiocore/src/model/DefaultConstructionSet_Impl.hpp
openstudiocore/src/model/Surface.cpp
openstudiocore/src/model/test/DefaultConstructionSet_GTest.cpp
openstudiocore/src/openstudio_lib/DefaultConstructionSetInspectorView.cpp
openstudiocore/src/openstudio_lib/DefaultConstructionSetInspectorView.hpp

Fix #974 - Add 'Adiabatic Surface Construction' to DefaultConstructionSet
**Changelog:**
* `IDDChange`: add the 'Adiabatic Surface Construction' field to the IDD for `OS:DefaultConstructionSet` as last field (takes in a Construction directly)
* Added to Model API (+Gtest), and OS App. Tested that inheritance in gridview works too. Demo in gif
* Added regression test in https://github.com/NREL/OpenStudio-resources/pull/67
*  FT didn't need any work since it relies on `Surface::construction`. VT isn't needed because it's added as a last field in IDD (tested too).
* Added a warning in `Surface::setOutsideBoundaryCondition('Adiabatic')` to tell user that this deletes the `SubSurfaces` as it wasn't clear to me and I did end up having a crash when testing.
* Before:
```ruby
m = …
```

Fix #974 - Add 'Adiabatic Surface Construction' to DefaultConstructionSet

---

openstudiocore/src/utilities/core/PathHelpers.cpp
openstudiocore/src/utilities/idf/IdfFile.cpp
openstudiocore/src/utilities/idf/Test/IdfFile_GTest.cpp

Fix #72 -  Passing non OSM/OSC/IDF files to load shouldn't return an initialized IdfFile/Model
**Changelog:**
* `IdfFile::m_load` returns False unless it can parse at least ONE valid IDF object
* Added a warning when trying to load an `OpenStudio::Model:Model` that doesn"t have `osc` or `osm` extension (just like OpenStudio::IdfFile::load would issue a warning if extension isn't `idf`)
```ruby
_m = OpenStudio::Model::Model::load("CMakeCache.txt")
[openstudio.setFileExtension] <0> Path p, 'CMakeCache.txt', has an unexpected file extension. Was expecting 'osm' or 'osc'.
[utilities.idf.IdfFile] <0> Unrecognizable object type '//Dependencies for the target'. Defaulting to 'Catchall'.
[utilities.idf.IdfFile] <0> Cannot find object type 'Catchall' in Idd. Placing data in Catchall object.
... …
```

Fix #72 -  Passing non OSM/OSC/IDF files to load shouldn't return an initialized IdfFile/Model

---

openstudiocore/src/utilities/idd/IddObject.cpp
openstudiocore/src/utilities/idd/Test/IddObject_GTest.cpp

Fix #3079 - Force unique names to match E+ new convention
Added unit test to match the ruby code in #3079.
Per conversion with @macumber I have modified `IddObject::references()` method to include a fake reference group when the object has none.

Fix #3079 - Force unique names to match E+ new convention

---

openstudiocore/src/model/UtilityBill.cpp
openstudiocore/src/utilities/sql/SqlFile.cpp
openstudiocore/src/utilities/sql/SqlFile.hpp
openstudiocore/src/utilities/sql/SqlFile_Impl.cpp
openstudiocore/src/utilities/sql/SqlFile_Impl.hpp
openstudiocore/src/utilities/sql/Test/SqlFile_GTest.cpp

Fix #745 - Use the 'Year' field from Sql file
Fix https://github.com/NREL/OpenStudio-measures/issues/138

Fix #745 - Use the 'Year' field from Sql file

---

openstudiocore/src/shared_gui_components/EditController.cpp
openstudiocore/src/shared_gui_components/EditView.cpp
openstudiocore/src/shared_gui_components/EditView.hpp
openstudiocore/src/shared_gui_components/WorkflowController.cpp
openstudiocore/src/shared_gui_components/WorkflowController.hpp

(Initially tried another approach in #3438, after discussion I am starting from a clean slate)
Fix #2798 - Show Uneditable measure name in addition to Display Name
Upon dragging a new measure:
* New: OSW 'measure_dir_name" goes to "Measure Directory Name" and cannot be modified
* OSW 'name' goes to "Name" as usual

Fix #2798 - Show Uneditable measure name in addition to Display Name

---

openstudiocore/CMakeLists.txt
openstudiocore/sketchup_plugin/openstudio/sketchup_plugin/resources/templates/MinimalTemplate.osm
openstudiocore/sketchup_plugin/openstudio/sketchup_plugin/resources/templates/empty.osm
openstudiocore/src/openstudio_app/Resources/default/hvac_library.osm
openstudiocore/src/openstudio_app/Resources/default/office_default.osm
openstudiocore/src/utilities/sql/Test/SqlFile_GTest.cpp

Revamp E+ section to allow building on windows, I had adjusted the 9.1.0 `ENV{ENERGYPLUSDIR}` in the UNIX block only.
Additional:
* Allow to place E+ zip/tar.gz in build folder and let Cmake deal with it (useful when you have several build folders, you can copy the new E+ tar.gz from one build folder to the others to avoid downloading 150 MB each time)
* Add status message to explain what's downloading too (I see a lot of "Downloading XX%" but you don't know whether it's radiance, Qt, Ruby, etc)

CMake adjustements for E+

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateCoilHeatingElectric.cpp
openstudiocore/src/model/CoilHeatingElectric.cpp
openstudiocore/src/model/CoilHeatingElectric.hpp

Fix #3487
* Change the coils addToNode methods to not set the 'Temperature Setpoint Node' field like it does now (it's an optional field)
* In the energyplus Forward Translator, if the field is blank at translation time, then set it to the supply outlet node of the coil (where a SPM:MixedAir will be created for you too)
Chose not to show the 'Temperature Setpoint Node' in OS App. I think this is going to be confusing for most users, and if an advanced user wants to set it, she can use the bindings to do so.

Fix #3487 - Consistent Setpoint Temperature Node for CoilHeatingElectric

---

openstudiocore/CMakeLists.txt
openstudiocore/pat/BuildPat.bat.in

Updating CMake path for release note docs as these have been moved from /docs to /developer/docs. 
Also updating the args for npm as the --no-optional was creating an error during the Windows 2019 build process.

update cmake path and remove --no-option npm arg

---

openstudiocore/src/utilities/data/Test/TimeSeries_GTest.cpp
openstudiocore/src/utilities/data/TimeSeries.cpp

Following https://github.com/NREL/OpenStudio/pull/3489 where I modified `TimeSeries::values(DateTime& start, DateTime& end)`, doing the same for `TimeSeries::value(DateTime&)` now
Also extended Gtests to test for TimeSeries that have no internal year.

Hotfix/sql_year part 2: Fix problem in TimeSeries::value(Datetime&)

---

openstudiocore/src/openstudio_app/OpenStudioApp.cpp
openstudiocore/src/openstudio_app/main.cpp
openstudiocore/src/utilities/core/ApplicationPathHelpers.cxx.in
openstudiocore/src/utilities/core/PathHelpers.cpp
openstudiocore/src/utilities/core/PathHelpers.hpp
openstudiocore/src/utilities/core/test/ApplicationPathHelpers_GTest.cpp

Fix #3158 and Fix #2802: symlink path problems
The problem was arising when you launch the uderlying executable (whatever the executable actually, could be OpenStudioApp, or openstudio, or openstudio_utilities_tests, etc) from the terminal when two conditions are met:
* You call something that is found in your PATH, and NOT in the current directory you are under
* That something is actually a symlink
I added some unit tests, some of which are Unix only because they rely on symlinks (while symlinks are possible on windows I don't think it'll work on all machines out of the box).
I also added one "weird" test that runs another test in another thread... I could see this being frown upon, but I don't see any other way to test this very specific thing otherwise.
Side note: now if you have …

Fix #3158: symlink path problems

---

openstudiocore/src/model/Building.cpp
openstudiocore/src/model/Building.hpp
openstudiocore/src/model/Building_Impl.hpp
openstudiocore/src/model/test/Building_GTest.cpp

Implement a full `Building::remove` method to delete objects rather than default to ParentObject::remove which will not call individual ModelObject::remove methods (and therefore in particular will delete a thermalZone but not properly disconnect it first leading to a crash)

Fix 3524: errors in Building::remove

---

.gitlab-ci.yml
developer/ruby/CheckOSMVersions.rb
developer/ruby/UpdateHVACLibrary.rb
openstudiocore/sketchup_plugin/openstudio/sketchup_plugin/user_scripts/On Demand Template Generators/resources/Master_Schedules.osm

Fix #3501 and Fix #3146: add script to pipeline to check for outdated OSM libraries

Fix #3501 #3146: add script to pipeline to check for outdated OSM libraries

---

openstudiocore/src/shared_gui_components/OSDoubleEdit.cpp
openstudiocore/src/shared_gui_components/OSIntegerEdit.cpp
openstudiocore/src/shared_gui_components/OSLineEdit.cpp
openstudiocore/src/shared_gui_components/OSQuantityEdit.cpp
openstudiocore/src/shared_gui_components/OSUnsignedEdit.cpp

The issue stems from the destructor of OSEdit classes
calling unbind. The unbind method does three things.
1. resets the member variables related to the ModelObject that is bound
2. removes some qt signal connections
3. calls setEnabled(false)
You can see these steps here https://github.com/NREL/OpenStudio/blob/1ae1cec65b25421bd2dabcb7501618a00338645b/openstudiocore/src/shared_gui_components/OSLineEdit.cpp#L152
During destruction of the widget it is item 3 that causes the issue,
because as the widget calls the setEnabled method, the focus event is triggered
and that causes a bunch of refreshing logic that we don't want because the overall
view is in a half destroyed state.
The solution is simply to not call unbind when the OSEdit classes are destroyed.
This is defensbile because
1. member …

Fix crash on mac related to os edit

---

openstudiocore/pat/CMakeLists.txt

Updating PAT sha in CMAKE to refer to the new PAT in repo. PAT updates include the new OpenStudio server for Window and Mac.

updating pat sha to ref new pat in gitrepo

---

ConanInstall.cmake

On Ubuntu I know force building boost_asio and websocket is unecessary (I tested it).
I see no reason that it would be different on mac. I will let CI confirm that. I have connected to the mac mini and wiped the following folders before opening this PR.
```
/bin/rm -Rf ~/.conan/data/openstudio_ruby/
/bin/rm -Rf ~/.conan/data/boost_asio/
/bin/rm -Rf ~/.conan/data/websocketpp/
```
CI will also test that https://github.com/NREL/conan-openstudio-ruby/pull/14 fixed the openstudio ruby DBM issue on Ubuntu

Simplify ConanInstall.cmake and do not force build stuff unless necessary

---

ConanInstall.cmake

Following https://github.com/bincrafters/conan-readline/pull/9 and https://github.com/bincrafters/conan-readline/pull/10, conan-readline now allows static on mac.
This PR is more for documentation purposes than anything else since I have already tested everything via push to an upstream branch here (https://github.com/NREL/OpenStudio/commit/ea54dc1052168d6dd421ef3ffd8d1909c77c6f02) and using it in OpenStudioApplication, cf https://github.com/NREL/OpenStudioApplication/pull/35. @tijcolem tested the resulting .dmg on mac and ensured that CLI works. I reproduced a build on a mac too, testing Debug. Works too.

Enable static conan-readline on mac

---

openstudiocore/resources/energyplus/ProposedEnergy+.idd
openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermalZone.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateThermostatSetpointDualSetpoint.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateZoneControlThermostatStagedDualSetpoint.cpp
openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateZone.cpp
openstudiocore/src/energyplus/Test/ThermostatSetpointDualSetpoint_GTest.cpp
openstudiocore/src/model/ThermostatSetpointDualSetpoint.cpp
openstudiocore/src/model/ThermostatSetpointDualSetpoint.hpp
openstudiocore/src/model/ThermostatSetpointDualSetpoint_Impl.hpp

Fix #3584 
* energyplus namespace: In E+, the `ZoneControl:Thermostat` has the numeric field `Temperature Difference Between Cutout And Setpoint` after the "extensible" groups, so until that's addressed (cf NREL/EnergyPlus#7484), I removed the extensible portion and am explicitly defining the four groups Control Object Type / Control Object Name, so I can add this field at the end.
* model namespace: this is added to the `OS:ThermostatSetpoint:DualSetpoint` object, and is handled in the FT. 
I didn't have time to build / test.

#3584 add Temperature Difference Between Cutout And Setpoint for ZoneControl:Thermostat

---

openstudiocore/resources/energyplus/ProposedEnergy+.idd
openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/CMakeLists.txt
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateFoundationKiva.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSurfacePropertyExposedFoundationPerimeter.cpp
openstudiocore/src/energyplus/ReverseTranslator.cpp
openstudiocore/src/energyplus/ReverseTranslator.hpp
openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateBuildingSurfaceDetailed.cpp
openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateFoundationKiva.cpp
openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateFoundationKivaSettings.cpp
openstudiocore/src/energyplus/ReverseTranslator/ReverseTranslateSurfacePropertyExposedFoundationPerimeter.cpp
openstudiocore/src/energyplus/Test/ReverseTranslator_GTest.cpp
openstudiocore/src/model/FoundationKiva.cpp
openstudiocore/src/model/FoundationKiva.hpp
openstudiocore/src/model/FoundationKiva_Impl.hpp
openstudiocore/src/model/ModelGeometry.i
openstudiocore/src/model/test/FoundationKiva_GTest.cpp
openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/osversion/VersionTranslator.hpp

Design doc: https://docs.google.com/document/d/1zu-kOTe3q22X2ukZKKg0vn7_2fvhZpakXeHZ05y1-LA/edit#

Use Custom Blocks in Foundation Kiva

---

openstudiocore/src/openstudio_lib/GridItem.cpp

Fix #3600: display plantLoop supply equipment in the same order as added **and** as the resulting `PlantEquipmentList` after ForwardTranslaton
See https://github.com/NREL/OpenStudio/issues/3600#issuecomment-511755968 for diagnostic and root cause.
Objects are now displayed in the same order as I added them:
I set the two HX to Control Type "CoolingSetpointModulated" (a **cooling** one). Tested that after FT I also get the same order:
```
PlantEquipmentList,
Plant Loop 1 Cooling Equipment List,    !- Name
HeatExchanger:FluidToFluid,             !- Equipment Object Type 1
Fluid-to-Fluid HX,                      !- Equipment Name 1
Chiller:Electric:EIR,                   !- Equipment Object Type 2
Chiller - Air Cooled,                   !- Equipment Name 2
HeatExchanger:FluidToFluid, …
```

Fix #3600: display plantLoop supply equipment in the same order as the resulting PlantEquipmentList after ForwardTranslaton

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/CMakeLists.txt
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitaryHeatCoolVAVChangeoverBypass.cpp
openstudiocore/src/energyplus/Test/AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass_GTest.cpp
openstudiocore/src/model/AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass.cpp
openstudiocore/src/model/AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass.hpp
openstudiocore/src/model/AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass_Impl.hpp
openstudiocore/src/model/test/AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass_GTest.cpp
openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml
openstudiocore/src/osversion/VersionTranslator.cpp

Fix #3639 - Add new Fields in AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass
The new choice is straightforward, so is the setter/getter for "Minimum Runtime Before Operating Mode Change".
Logic for the "Plenum or Mixer Inlet Node":
* `AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass::AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass` ctor will create an OS:Node and connect to it via an OS:ConnectionObject (similar to for eg the ThermalZone ctor that creates a Node for "Zone Air Node").
* `bool AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass::setPlenumorMixer(const Mixer& mixer)` will accept a `AirLoopHVACZoneMixer` or a `AirLoopHVACReturnPlenum` if it's on the *same* AirLoopHVAC as the unitary system is on, and connect to it. It will add a new `Inlet Node Name` extensible field to the mixer object. …

Add new Fields in AirLoopHVACUnitaryHeatCoolVAVChangeoverBypass 

---

openstudiocore/CMakeLists.txt
openstudiocore/pat/CMakeLists.txt
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateTableMultiVariableLookup.cpp
openstudiocore/src/model/CoilCoolingDXSingleSpeed.cpp
openstudiocore/src/model/CoilCoolingDXTwoSpeed.cpp
openstudiocore/src/model/ExternalFile.cpp
openstudiocore/src/utilities/sql/Test/SqlFileFixture.cpp
openstudiocore/src/utilities/sql/Test/SqlFileFixture.hpp
openstudiocore/src/utilities/sql/Test/SqlFile_GTest.cpp

This PR updates EnergyPlus: 
* from : https://github.com/NREL/EnergyPlus/releases/tag/v9.2.0-IOFreeze 
* to: https://github.com/NREL/EnergyPlus/releases/tag/v9.2.0-Alpha2
It also updates openstudio-gems.tar.gz for the new openstudio-standards, openstudio-extension and openstudio-workflow gem versions. 
I ran a full build and there are a few issues: 
1 ) Windows CI server hit an exceeded path limit of 260 chars due to the new paths in the openstudio-standards gem.  It looks like I can fix this by setting the reg key 'LongPathsEnabled' to 1 which then allows 4x the path lengths. Rebuilding now to see if that resolves it. Here was the error
`
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(974,5): error MSB4023: Cannot evaluate the item metadata …

V2.9.0 rc1

---

openstudiocore/src/openstudio_lib/EMSInspectorView.cpp

Fix #3617 Fix Typo in OS App for "Acuators"

Fix #3617: typo in OS app for "Actuators"

---

openstudiocore/src/openstudio_app/Resources/default/hvac_library.osm

Fix #3680 HeatPumpWaterToWaterEquationFit frequired fields not initialized in Hvac_library
Something must have gone wrong since I see VT rules were added, cf https://github.com/jmarrec/OpenStudio/commit/19037a79c66fb2ffb849095ee37c7874e2846963#diff-f40f617c05070be7f31161a497d2d1ae. I suppose hvac_library.osm was updated BEFORE the VT rules were written, or the version was bumped manually.
----
After fix: 
**HeatPump:WaterToWater:EquationFit:Cooling**
**HeatPump:WaterToWater:EquationFit:Heating**

HeatPumpWaterToWaterEquationFit required fields not initialized in hvac_library

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateHeaderedPumpsConstantSpeed.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateHeaderedPumpsVariableSpeed.cpp
openstudiocore/src/model/HeaderedPumpsConstantSpeed.cpp
openstudiocore/src/model/HeaderedPumpsConstantSpeed.hpp
openstudiocore/src/model/HeaderedPumpsConstantSpeed_Impl.hpp
openstudiocore/src/model/HeaderedPumpsVariableSpeed.cpp
openstudiocore/src/model/HeaderedPumpsVariableSpeed.hpp
openstudiocore/src/model/HeaderedPumpsVariableSpeed_Impl.hpp
openstudiocore/src/model/test/HeaderedPumpsConstantSpeed_GTest.cpp
openstudiocore/src/model/test/HeaderedPumpsVariableSpeed_GTest.cpp
openstudiocore/src/osversion/VersionTranslator.cpp

Fix #3553
* Added methods to model API
* Added methods to FT
* Added Version Translation (and tested it, in particular on hvac_library.osm)
* Extended model test for new fields
* Tested that OpenStudio-resources test headered_pumps (both rb and osm) still run and have zero difference with previous run

Add missing methods for HeaderedPumpsConstantSpeed and HeaderedPumpsVariableSpeed

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAvailabilityManagerNightCycle.cpp
openstudiocore/src/energyplus/Test/AvailabilityManagerNightCycle_GTest.cpp
openstudiocore/src/model/AvailabilityManagerNightCycle.cpp
openstudiocore/src/model/AvailabilityManagerNightCycle.hpp
openstudiocore/src/model/AvailabilityManagerNightCycle_Impl.hpp
openstudiocore/src/model/FanConstantVolume.cpp
openstudiocore/src/model/FanVariableVolume.cpp
openstudiocore/src/model/ScheduleTypeRegistry.cpp
openstudiocore/src/model/test/AvailabilityManagerNightCycle_GTest.cpp
openstudiocore/src/openstudio_lib/library/OpenStudioPolicy.xml
openstudiocore/src/osversion/VersionTranslator.cpp
openstudiocore/src/osversion/VersionTranslator.hpp

Fix #3568 and Fix #3702 
* add `Schedule AvailablityManagerNightCycle::applicabilitySchedule` (defaults to m.alwaysOnDiscreteSchedule), `AvailablityManagerNightCycle::setApplicabilitySchedule(Schedule&)` 
* Add a helper getter `boost::optional<Schedule> AvailablityManagerNightCycle::fanSchedule()` which will check if there's an AirLoopHVAC, and if so, will return its Availability Schedule (like the FT does already)
----
Fix #3707: Hide the control zones modelObjectList and the Fan Schedule in OS App
----
Relates #3627: Add a LOG Info if trying to use FanConstantVolume::setAvailabilitySchedule or FanVariableVolume::setAvailabilitySchedule while these fans are on a AirLoopHVAC (since they will be overriden)
```
fan.addToNode(airLoopHVAC.supplyOutletNode)
fan.setAvailabilitySchedule(sch) …
```

Add methods to AvailablityManagerNightCycle (applicabilitySchedule) and hide attributes in OS App

---

openstudiocore/src/model/ZonePropertyUserViewFactorsBySurfaceName.cpp
openstudiocore/src/utilities/idf/WorkspaceExtensibleGroup.cpp
openstudiocore/src/utilities/idf/WorkspaceExtensibleGroup.hpp

close #3713
Time for the test case reference in #3713 is now 
kbenne-27067s:OpenStudio kbenne$ time ./build/Products/openstudio build/test.rb
49 view factors => 0.0 sec
64 view factors => 0.0 sec
81 view factors => 0.01 sec
100 view factors => 0.01 sec
121 view factors => 0.01 sec
144 view factors => 0.02 sec
169 view factors => 0.02 sec
196 view factors => 0.04 sec
225 view factors => 0.05 sec
256 view factors => 0.06 sec
289 view factors => 0.08 sec
324 view factors => 0.11 sec
361 view factors => 0.14 sec
400 view factors => 0.18 sec
441 view factors => 0.23 sec
484 view factors => 0.3 sec
529 view factors => 0.4 sec
576 …

Improve the runtime performance of ViewFactor

---

CMakeLists.txt
ConanInstall.cmake
ProjectMacros.cmake
src/cli/CMakeLists.txt
src/utilities/CMakeLists.txt

Fix #3607
Note that I had to adjust the add_custom_command to pass the SWIG_LIB env variable, since the exe given by conan has swiglib = the one on the build box (CI) used to build it
It worked fine on Ubuntu 18.04, and I was able to use the resulting bindings. I'll let CI produce binaries for other platforms and test.

Use conan swig_installer 4.0

---

openstudiocore/ProjectMacros.cmake

Fix #2796:
I finally figured out why I had so much problems reproducing this issue regardless of the platform I was using (macOS or Ubuntu).
Turns out that if you want to reproduce repeatedly you need to be very literal with the wiki build instructions, and use `make` as in **monothread** make. Using `make -j 16` or just `ninja` (=`ninja -j $(nproc)`) will not exhibit the race condition where **MAKE_SWIG_TARGET** is called before **GenerateIddFactoryRun** actually runs.

Fix #2796 - No rule to make target 'src/utilities/idd/IddFieldEnums.ixx'

---

openstudiocore/src/energyplus/ForwardTranslator.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateInternalMass.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSubSurface.cpp
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateSurface.cpp

Fix #3669: make order deterministic for SurfacePropertyConvectionCoeficients and SurfacePropertyExposedPerimeter
Basically Surface and SubSurface FTs are responsible to call the translation of these objects.

Fix #3669: make order deterministic for SurfacePropertyConvectionCoeficients and SurfacePropertyExposedPerimeter

---

openstudiocore/src/model/Building.cpp
openstudiocore/src/model/Building.hpp
openstudiocore/src/model/BuildingStory.cpp
openstudiocore/src/model/BuildingStory.hpp
openstudiocore/src/model/BuildingStory_Impl.hpp
openstudiocore/src/model/Building_Impl.hpp
openstudiocore/src/model/test/BuildingStory_GTest.cpp
openstudiocore/src/model/test/Building_GTest.cpp

Fix #3413 - Add `getDefaultSchedule(defaultScheduleType)` for:

Add `getDefaultSchedule(defaultScheduleType)` for `Building` and `BuildingStory`

---

openstudiocore/src/model/ScheduleTypeRegistry.cpp
openstudiocore/src/model/ScheduleTypeRegistry.hpp

Fix #2991 - ScheduleTypeRegistry isCompatible shouldn't return a schedule that does have a lower/upper limit when the ScheduleType we're looking for doesn't.

ScheduleTypeRegistry adjustment in looking for a compatible ScheduleTypeLimits

---

src/cli/embedded_help.rb

This addresses #3746 but is specific to Windows. Current ruby windows build via conan https://github.com/NREL/conan-openstudio-ruby provides msvc native json/ext statically linked in so this check is no longer needed.

removing json/ext check as this is statically linked in cli

---

src/cli/embedded_help.rb

This is a pull request for the `v3.0-pre` branch.  It comments out a couple warnings that are interfering with stdout from our OS workflow.

3.0-pre comment out warnings

---

openstudiocore/resources/model/OpenStudio.idd
openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACUnitarySystem.cpp
openstudiocore/src/model/AirLoopHVACUnitarySystem.cpp
openstudiocore/src/model/AirLoopHVACUnitarySystem.hpp
openstudiocore/src/model/AirLoopHVACUnitarySystem_Impl.hpp
openstudiocore/src/model/test/AirLoopHVACUnitarySystem_GTest.cpp

Fix #3280  AirLoopHVAC:UnitarySystem add missing control type SingleZoneVAV
Also N2, \field `DOAS DX Cooling Coil Leaving Minimum Air Temperature` in OS (called `Minimum Supply Air Temperature` in E+ now) becomes `autosizable`. And the maximum is raised to 20 too.
----
Note: IDD is falling out of sync with E+, lots of field renames, typos, etc:
* A bunch other fields are renamed too, like Supply Air Flow Rate Method During Cooling Operation which is Cooling Supply Air Flow Rate Method
* Some other fields have a typo in OS and not in E+, eg
OS:Ancilliary On-Cycle Electric Power
E+:Ancillary On-Cycle Electric Power

 AirLoopHVAC:UnitarySystem add missing control type SingleZoneVAV and make Minimum Supply Air Temperatre autosizable

---

openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateShadingControl.cpp

Removes superfluous warning about daylighting in the ShadingControl FT code. This object does not require a daylighting control, so the warning is confusing/misleading.

Removes ShadingControl warning

---

ProjectMacros.cmake
embedded/CMakeLists.txt
src/cli/CMakeLists.txt
src/generateiddfactory/CMakeLists.txt
src/install_utility/CMakeLists.txt
src/utilities/CMakeLists.txt

OpenSSL is an exception
Read the issue, and the specific OpenSSL comment here: https://github.com/conan-io/conan/issues/6269#issuecomment-572431739

Change CONAN_PKG::xxx casing following upstream breaking changes.

---

src/utilities/CMakeLists.txt

OpenSSL renamed to openssl (lowercase)

---

CMakeLists.txt
debian/postinst.in
debian/postrm.in

Companion PR for https://github.com/NREL/OpenStudioApplication/pull/70
I'm using a postinst script here too, because if you install OSApp first then the symlink at /usr/bin/openstudio will already exist and it'll fail if you try to install OpenStudio after that. Also, this allows installing 2 openstudio (sdk) versions too.
I installed OSApp.
```
ls -la /usr/local/bin/op*
lrwxrwxrwx 1 root root 58 Jan 14 09:14 /usr/local/bin/openstudio -> /usr/local/openstudioapplication-1.0.0-pre1/bin/openstudio
lrwxrwxrwx 1 root root 58 Jan 14 09:14 /usr/local/bin/openstudio-3.0.0-rc1 -> /usr/local/openstudioapplication-1.0.0-pre1/bin/openstudio
```
Then I installed OpenStudio package from this PR, without a problem.
```
lrwxrwxrwx 1 root root 47 Jan 14 09:17 /usr/local/bin/openstudio -> …
```

Allow Installing both OpenStudio (SDK) and OpenStudioApplication via Deb package

---

developer/doc/ReleaseNotes/OpenStudio_Release_Notes_3_0_0.md

@kbenne @tijcolem @joseph-robertson 
I started a draft of the 3.x release notes, mostly initially to catalog the major changes I've made (as requested by @kbenne on a few of my PRs), but might as well try to do something clean directly.
Going forward, I think we should start a template release notes markdown file right after a release so we have a centralized place to at least catalogue API-breaking changes and major fixes and new features (stuff other than trivial bug fixes), and ensure we do not forget.

Add a Release Notes document for 3.0.0

---

src/model/Surface.cpp
src/model/test/Surface_GTest.cpp

Fix failing test (follow up #3867)
```
2063: [ RUN      ] ModelFixture.SurfacePropertyOtherSideCoefficients
2063: C:\src\OpenStudio\src\model\test\Surface_GTest.cpp(865): error: Expected equality of these values:
2063:   "SunExposed"
2063:   wall1.sunExposure()
2063:     Which is: "NoSun"
2063: C:\src\OpenStudio\src\model\test\Surface_GTest.cpp(866): error: Expected equality of these values:
2063:   "WindExposed"
2063:   wall1.windExposure()
2063:     Which is: "NoWind"
2063: C:\src\OpenStudio\src\model\test\Surface_GTest.cpp(870): error: Expected equality of these values:
2063:   "SunExposed"
2063:   wall1.sunExposure()
2063:     Which is: "NoSun"
2063: C:\src\OpenStudio\src\model\test\Surface_GTest.cpp(871): error: Expected equality of these values:
2063:   "WindExposed"
2063: …
```

Fix failing ModelFixture.SurfacePropertyOtherSideCoefficients test (follow up #3867)

---

CMakeLists.txt
FetchRubyMinGW.cmake

- needed for later consumption by OpenStudioApplication
when building ModelEditor ruby bindings

Separate and package ruby mingw fetch commands

---

ruby/CMakeLists.txt
ruby/openstudio.rb
src/utilities/core/Singleton.hpp

Move to dynamic linking of openstudiolib.dll to ruby openstudio.dll to pretend like we have some control over the Undefined Behavior caused by ruby's definition of `fclose` and other system library functions.

Fix ruby windows crash with system ruby

---

src/cli/openstudio_cli.rb

Prevents an error in OS CLI exception handling when e.backtrace is nil. 
Example:
```
C:/openstudio-3.0.0-beta/bin/openstudio.exe -e "require 'rubocop/rake_task'" -e "RuboCop::RakeTask.new(:rubocop) do |t| t.options = ['--auto-correct', '--format', 'simple', '--only', 'Layout,Lint/DeprecatedClassMethods,Lint/StringConversionInInterpolation,Style/AndOr,Style/HashSyntax,Style/Next,Style/NilComparison,Style/RedundantParentheses,Style/RedundantSelf,Style/ReturnNil,Style/SelfAssignment,Style/StringLiterals,Style/StringLiteralsInInterpolation'] end" -e "Rake.application[:rubocop].invoke"
Ignoring pycall-1.2.1 because its extensions are not built. Try: gem pristine pycall --version 1.2.1
Running RuboCop...
2 files inspected, no offenses detected
Error executing argv: ["-e", "require …
```

Prevent CLI error

---

src/cli/embedded_help.rb
src/cli/openstudio_cli.rb

This is significant @tijcolem @nllong @brianlball
Previously, when --bundle is used then even the baked in libraries from openstudio-gems are made unavailable, with this change the baked in openstudio-gems (even native ones like pycall) are still available. Anything defined in --bundle will override the baked in stuff. So for instance it is possible to define a bundle with a custom version of the OpenStudio standards gem and that version of standards will be used instead of the baked in version.
close #3957
close #3933
Also, minor fix to annoying messages shown when NOT using --bundle...
"Ignoring jaro_winkler-1.5.4 because its extensions are not built. Try: gem pristine jaro_winkler --version 1.5.4"
This is not true as jaro_winkler is actually still available from the embedded system. …

Allow embedded gems even with --bundle

---

Jenkinsfile_develop_linux
Jenkinsfile_develop_osx
Jenkinsfile_develop_windows

Changing Jenkins to run CI for each platform (Windows, Linux, OS) separately versus parallel. 
This is preferred as you can replay a job specific to a platform versus having to replay a job to run on all platforms.

adding separate Jenkins files for each platform

---

src/model/Model.hpp
src/model/Model_Common_Include.i

Reverts NREL/OpenStudio#4010
Need to roll back this commit as the Windows build failed which appears to be due to csharp issue. 
See build of commit: [0607f8775e3ec1049b9b618b84ddaf0a34788011](https://github.com/NREL/OpenStudio/commit/0607f8775e3ec1049b9b618b84ddaf0a34788011)  
and the CI for this build  -  https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-develop-nightly/detail/openstudio-develop-nightly/554/pipeline/ 
The previous commit [e876c5a269c0fd7a766f4afd0fa46379bc3228e1](https://github.com/NREL/OpenStudio/commit/e876c5a269c0fd7a766f4afd0fa46379bc3228e1) 
is clean on Windows - https://ci.commercialbuildings.dev/blue/organizations/jenkins/openstudio-develop-nightly/detail/openstudio-develop-nightly/552/pipeline

Revert "#4007 - Model objects returned in inconsistent order"

---

src/cli/test/bundle_git/test.rb
src/utilities/bcl/RemoteBCL.cpp

Fixes #4014 
Seems host `bcl.nrel.gov` can be slow to download for certain bcl components. For instance, in our unit tests, component `a10331a0-edc7-0131-840c-48e0eb16a403` can exceed the cpprestsdk default 30 sec response time which closes the client handle and results in a unit test failure.  
You can manually reproduce the slow response time by running a simple wget to the api endpoint for that component: 
`wget https://bcl.nrel.gov/api/component/download?uids=a10331a0-edc7-0131-840c-48e0eb16a403 `
This can change of course due to client/server network speeds.   
Increasing from 30 to 60 seems to fix.

Fix #4014 download from BCL

---

ConanInstall.cmake

Pro: we have zero chance of pulling something else. Fully reproducible builds
Cons: whenever we want to update a dependency, we'll have to bump the revision in OpenStudio/ConanInstall.cmake
If we do not pin dependencies, we could simply upload a new recipe revision, and delete the old one from the remote, or pass UPDATE to conan cmake run. I don't like passing UPDATE to conan_cmake_run actually  because it has to query bintray for changes everytime you run cmake (which takes time, doesn't work offline, etc)
Note: the pinning of deps really matter a lot of openstuido_ruby but not so much for the rest of the deps. Because we're unlikely going to bump a dep like boost for no reason without also bumping the version (eg boost/1.74...)

Pin the actual recipe revisions for all conan dependencies

---

src/lib/CMakeLists.txt
src/utilities/UtilitiesSql.i
src/utilities/sql/CMakeLists.txt
src/utilities/sql/PreparedStatement.cpp
src/utilities/sql/PreparedStatement.hpp
src/utilities/sql/SqlFile_Impl.hpp

Addresses #4126 
- Move implementation of PreparedStatement into .cpp file
- Remove hack for previous ruby fix
- Remove now unnecessary extra linkage to sqlite3
Note: this has been tested to make sure the previous Ruby / Sqlite bug had not regressed.

V3.1.0 fixed sqlite3 linkage

---

CMakeLists.txt

avoid this error:
```
** Severe  ** Failed to import module "<Module Name>"
**   ~~~   ** Python error description follows: 
**   ~~~   ** ModuleNotFoundError("No module named 'pyenergyplus'")
```
when trying to run pyems via openstudio.

include pyenergyplus directory from the installer

---

src/utilities/bcl/test/BCL_GTest.cpp
src/utilities/sql/Test/SqlFile_GTest.cpp

- fixes #4043 
- This changes a couple of the BCL tests. It can take a long time (minutes) to fetch certain components via the  https://bcl.nrel.gov/, so by changing the component in the test, it now succeeds and doesn't time out.  This is better than disabling the test altogether.   This also disables the download compoent step in RemoteBCL as the component fetched in the previous query was timing out. This step is redundant as it's already being tested in  GetComponentByUID so I think it's safe to comment out. It can be uncommented out when https://bcl.nrel.gov/  no longer experiences high latency when downloading select components.

Issue_4043 

---

src/cli/embedded_help.rb

fix #4132   Add to the existing regex to match for lower and upper case letters

fix issue_4132 - hande lower case window drive letters

---

developer/doc/Building and Testing OpenStudio.md

resolves #4058 
Removed SketchUp references in building and testing docs and updates info the current workflow that supports 3.x.x series. We should create a separate page for OpenStudio release process as it was previously included in this document.

Updating the docs for building and testing for 3.x.x series. 

---

.github/workflows/cppcheck.yml

Using container to run cppcheck v2.3 as this is no longer available via snap.

Use cppcheck container

---

.github/workflows/python_bindings.yml
python/find_pypi_tag.py

https://github.com/NREL/OpenStudio/runs/1764809039?check_suite_focus=true#step:4:41
The script to parse the available version from testpypi increments +1 by default, but for testing we shouldn't do that obviously.

Fix issue with the test portion of the python bindings workflow (no +1 for version)

---

resources/model/OpenStudio.idd

Add missing \ip-units following #4157
```diff
OS:Coil:Cooling:Water:Panel:Radiant,
N7 , \field Maximum Chilled Water Flow Rate
\required-field
\autosizable
\type real
\units m3/s
+       \ip-units gal/min
```

Hotfix: Add missing \ip-units following #4157

---

CMakeLists.txt
resources/CMakeLists.txt
resources/energyplus/5ZoneAirCooled/in.idf
resources/energyplus/BestestEx/in.idf
resources/energyplus/Daylighting_Office/in.idf
resources/energyplus/Daylighting_School/in.idf
resources/energyplus/HospitalBaseline/in.idf
resources/energyplus/NewFileTemplate.idf
resources/energyplus/Office_With_Many_HVAC_Types/in.idf
resources/energyplus/RefLargeOffice/RefBldgLargeOfficeNew2004_Chicago.idf
resources/energyplus/ScheduleFile/in.idf
resources/energyplus/SimpleSurfaces/4ZoneWithShading_Simple_2.idf
resources/energyplus/SimpleSurfaces/SimpleSurfaces_Reference.idf
resources/energyplus/SimpleSurfaces/SimpleSurfaces_Relative.idf
resources/energyplus/SmallOffice/SmallOffice.idf
resources/energyplus/ZoneBoundaryCondition/Bug_486_zone_bdr_test.idf
resources/utilities/Idf/CommentTest.idf
resources/utilities/Idf/DosLineEndingTest.idf
resources/utilities/Idf/FormatPropertyTest_Formatted.idf
resources/utilities/Idf/FormatPropertyTest_Unformatted.idf
resources/utilities/Idf/MixedLineEndingTest.idf
resources/utilities/Idf/UnixLineEndingTest.idf
resources/utilities/SqlFile/1ZoneEvapCooler-V9-5-0-IOFreeze.idf
resources/utilities/SqlFile/update_all.sh
ruby/test/epJSON_Test.rb
src/energyplus/Resources/LCCusePriceEscalationDataSet2011.idf
src/epjson/test/epJSONTranslator_GTest.cpp
src/model/ConstructionAirBoundary.hpp
src/utilities/idf/Test/WorkspaceObject_GTest.cpp
src/utilities/sql/Test/SqlFile_GTest.cpp

The "remove old extracted dir" was nested inside the case where the new + tar.gz doesn't exist yet. So it worked the first time, but not the second time you switched back. This should fix it, and would avoid CI problems. 
I transitioned the IDF Files to 9.5, added the Sql test for 9.5 (will redo that part when 9.5 official is out), and fixed the failing tests.
Also fixed the cppcheck warnings

Fix issues when building back and forth between E+ versions + Fix test failures + fix cppcheck warnings

---

src/cli/main.cpp

Fixes #4252 
Not sure why this takes so long to include rubocop using the cli but it might probably related to #4249

Fix #4252 - Error requiring rubocop

---

resources/model/OpenStudio.idd
src/model/ControllerMechanicalVentilation.cpp
src/model/test/AirLoopHVAC_GTest.cpp

This aligns the default value of the oa method between
ControllerMechanicalVentilation and SizingSystem.
close #4131

Coordinate default values for outdoor air method

---

ConanInstall.cmake

Fix #4201. 
Bintray is sunsetting as of 2021-05-01 so moving to new remote.  
Build recipes and binary packages have been transferred to new remote.

update conan remotes for bintray sunset

---

src/model/SubSurface.cpp
src/model/SubSurface.hpp
src/utilities/sql/SqlFile.hpp

HotFix #4550 - Remove getExteriorFenestrationValue from public API
I missed this during the review, only realized when reviewing the OpenStudio-resources test

HotFix #4550 - Remove getExteriorFenestrationValue from public API

---

CMakeLists.txt
ConanInstall.cmake

Resolves https://github.com/NREL/OpenStudio/issues/4574
- Enabled options in cmake to build centos7 packages from conan remote https://conan.openstudio.net/artifactory/api/conan/openstudio-centos 
- Uploaded openstudio centos7 binaries compiled with gcc10 to openstudio-centos remote so c++20 will work. This is needed due to glibc issue. see reason [here](https://github.com/NREL/OpenStudio/blob/develop/developer/conan/binary_incompatility_glibc.md))
- Updated E+ package sha.

Enable centos7 for c++20

---

.github/workflows/python_bindings.yml

This fixes python bindings for mac. Upgrades the GitHub Actions runner to use macos 11 and the latest SDK available at this time. macos 10.15 is deprecated anyway and will be removed in Dec.

update github action macos runner to use 11 and xcode 13.2.1

---

ruby/engine/openstudio_cli.rb

This fixes an issue on Windows where **cmd.exe** treats single quotes in args as string literals. 
For example, running this on cmd.exe fails 
`C:\openstudio-3.5.0-rc1\bin\openstudio.exe run -w 'C:\openstudio-3.5.0-rc1\Examples\compact_osw\compact_ruby_only.osw'`
```
Error executing argv: ["run", "-w", "'C:\\openstudio-3.5.0-rc1\\Examples\\compact_osw\\compact_ruby_only.osw'"]
Error: Invalid argument @ realpath_rec - D:/OSN/build/'C: in eval:510:in `realpath'
eval:510:in `realpath'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:141:in `realpath'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/run.rb:141:in `block in initialize'
:/ruby/2.7.0/gems/openstudio-workflow-2.3.1/lib/openstudio/workflow/registry.rb:67:in `register' …
```

Windows arg parsing

---

CMakeLists.txt

short term solution of issue #5063 
https://github.com/NREL/OpenStudio/issues/5063
https://github.com/NREL/OpenStudio/wiki/Configuring-OpenStudio-SDK-Build-Environments-(3.X.X-or-greater)#windows-1
Since it required 1.8.7 or 1.8.8 I specify the requirement.
Since it only effect the documentation generation flag, not much test need to be done.

Specify the requirement of Doxygen.

---

ruby/engine/test/RubyEngine_GTest.cpp

@jmarrec see the description of what is going on in the [issue](https://github.com/NREL/OpenStudio/issues/5155) I suppose it is possible the issue is local to me. 
I'm working with @wenyikuang to get the CI passing the ruby tests.

5155 ruby engine fixture.wrong method measure

---

src/energyplus/ForwardTranslator/ForwardTranslateAirLoopHVACOutdoorAirSystem.cpp

Remove AVM for AirLoopHVACOutdoorAirSystem
